<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("cities")->truncate();
        $citys = [
            ["prefectures_id" => 1, "name" => "札幌市"],
            ["prefectures_id" => 1, "name" => "函館市"],
            ["prefectures_id" => 1, "name" => "小樽市"],
            ["prefectures_id" => 1, "name" => "旭川市"],
            ["prefectures_id" => 1, "name" => "室蘭市"],
            ["prefectures_id" => 1, "name" => "釧路市"],
            ["prefectures_id" => 1, "name" => "帯広市"],
            ["prefectures_id" => 1, "name" => "北見市"],
            ["prefectures_id" => 1, "name" => "夕張市"],
            ["prefectures_id" => 1, "name" => "岩見沢市"],

            // 青森県
            ['prefectures_id' => 2, 'name' => '青森市'],
            ['prefectures_id' => 2, 'name' => '弘前市'],
            ['prefectures_id' => 2, 'name' => '八戸市'],
            ['prefectures_id' => 2, 'name' => '黒石市'],
            ['prefectures_id' => 2, 'name' => '五所川原市'],
            ['prefectures_id' => 2, 'name' => '十和田市'],
            ['prefectures_id' => 2, 'name' => '三沢市'],
            ['prefectures_id' => 2, 'name' => 'むつ市'],
            ['prefectures_id' => 2, 'name' => 'つがる市'],
            ['prefectures_id' => 2, 'name' => '平川市'],

            // 岩手県
            ['prefectures_id' => 3, 'name' => '盛岡市'],
            ['prefectures_id' => 3, 'name' => '宮古市'],
            ['prefectures_id' => 3, 'name' => '大船渡市'],
            ['prefectures_id' => 3, 'name' => '花巻市'],
            ['prefectures_id' => 3, 'name' => '北上市'],
            ['prefectures_id' => 3, 'name' => '久慈市'],
            ['prefectures_id' => 3, 'name' => '遠野市'],
            ['prefectures_id' => 3, 'name' => '一関市'],
            ['prefectures_id' => 3, 'name' => '陸前高田市'],
            ['prefectures_id' => 3, 'name' => '釜石市'],
            ['prefectures_id' => 3, 'name' => '二戸市'],
            ['prefectures_id' => 3, 'name' => '八幡平市'],
            ['prefectures_id' => 3, 'name' => '奥州市'],
            ['prefectures_id' => 3, 'name' => '滝沢市'],

            // 宮城県
            ['prefectures_id' => 4, 'name' => '仙台市'],
            ['prefectures_id' => 4, 'name' => '石巻市'],
            ['prefectures_id' => 4, 'name' => '塩竈市'],
            ['prefectures_id' => 4, 'name' => '気仙沼市'],
            ['prefectures_id' => 4, 'name' => '白石市'],
            ['prefectures_id' => 4, 'name' => '名取市'],
            ['prefectures_id' => 4, 'name' => '角田市'],
            ['prefectures_id' => 4, 'name' => '多賀城市'],
            ['prefectures_id' => 4, 'name' => '岩沼市'],
            ['prefectures_id' => 4, 'name' => '登米市'],
            ['prefectures_id' => 4, 'name' => '栗原市'],
            ['prefectures_id' => 4, 'name' => '東松島市'],
            ['prefectures_id' => 4, 'name' => '大崎市'],
            ['prefectures_id' => 4, 'name' => '富谷市'],

            // 秋田県
            ['prefectures_id' => 5, 'name' => '秋田市'],
            ['prefectures_id' => 5, 'name' => '能代市'],
            ['prefectures_id' => 5, 'name' => '横手市'],
            ['prefectures_id' => 5, 'name' => '大館市'],
            ['prefectures_id' => 5, 'name' => '男鹿市'],
            ['prefectures_id' => 5, 'name' => '湯沢市'],
            ['prefectures_id' => 5, 'name' => '鹿角市'],
            ['prefectures_id' => 5, 'name' => '由利本荘市'],
            ['prefectures_id' => 5, 'name' => '大仙市'],
            ['prefectures_id' => 5, 'name' => '潟上市'],
            ['prefectures_id' => 5, 'name' => '北秋田市'],
            ['prefectures_id' => 5, 'name' => 'にかほ市'],
            ['prefectures_id' => 5, 'name' => '仙北市'],

            // 山形県
            ['prefectures_id' => 6, 'name' => '山形市'],
            ['prefectures_id' => 6, 'name' => '米沢市'],
            ['prefectures_id' => 6, 'name' => '鶴岡市'],
            ['prefectures_id' => 6, 'name' => '酒田市'],
            ['prefectures_id' => 6, 'name' => '新庄市'],
            ['prefectures_id' => 6, 'name' => '寒河江市'],
            ['prefectures_id' => 6, 'name' => '上山市'],
            ['prefectures_id' => 6, 'name' => '村山市'],
            ['prefectures_id' => 6, 'name' => '長井市'],
            ['prefectures_id' => 6, 'name' => '天童市'],
            ['prefectures_id' => 6, 'name' => '東根市'],
            ['prefectures_id' => 6, 'name' => '尾花沢市'],
            ['prefectures_id' => 6, 'name' => '南陽市'],

            // 福島県
            ['prefectures_id' => 7, 'name' => '福島市'],
            ['prefectures_id' => 7, 'name' => '会津若松市'],
            ['prefectures_id' => 7, 'name' => '郡山市'],
            ['prefectures_id' => 7, 'name' => 'いわき市'],
            ['prefectures_id' => 7, 'name' => '白河市'],
            ['prefectures_id' => 7, 'name' => '須賀川市'],
            ['prefectures_id' => 7, 'name' => '喜多方市'],
            ['prefectures_id' => 7, 'name' => '相馬市'],
            ['prefectures_id' => 7, 'name' => '二本松市'],
            ['prefectures_id' => 7, 'name' => '田村市'],
            ['prefectures_id' => 7, 'name' => '南相馬市'],
            ['prefectures_id' => 7, 'name' => '伊達市'],
            ['prefectures_id' => 7, 'name' => '本宮市'],
            ['prefectures_id' => 7, 'name' => '大玉村'],
            ['prefectures_id' => 7, 'name' => '桑折町'],
            ['prefectures_id' => 7, 'name' => '国見町'],
            ['prefectures_id' => 7, 'name' => '水戸市'],
            ['prefectures_id' => 7, 'name' => '日立市'],
            ['prefectures_id' => 7, 'name' => '土浦市'],
            ['prefectures_id' => 7, 'name' => '古河市'],
            ['prefectures_id' => 7, 'name' => '石岡市'],
            ['prefectures_id' => 7, 'name' => '結城市'],
            ['prefectures_id' => 7, 'name' => '龍ケ崎市'],
            ['prefectures_id' => 7, 'name' => '下妻市'],
            ['prefectures_id' => 7, 'name' => '常総市'],
            ['prefectures_id' => 7, 'name' => '常陸太田市'],
            ['prefectures_id' => 7, 'name' => '高萩市'],
            ['prefectures_id' => 7, 'name' => '北茨城市'],
            ['prefectures_id' => 7, 'name' => '笠間市'],
            ['prefectures_id' => 7, 'name' => '取手市'],
            ['prefectures_id' => 7, 'name' => '牛久市'],
            ['prefectures_id' => 7, 'name' => 'つくば市'],
            ['prefectures_id' => 7, 'name' => 'ひたちなか市'],
            ['prefectures_id' => 7, 'name' => '鹿嶋市'],
            ['prefectures_id' => 7, 'name' => '潮来市'],
            ['prefectures_id' => 7, 'name' => '守谷市'],
            ['prefectures_id' => 7, 'name' => '常陸大宮市'],
            ['prefectures_id' => 7, 'name' => '那珂市'],
            ['prefectures_id' => 7, 'name' => '筑西市'],
            ['prefectures_id' => 7, 'name' => '坂東市'],
            ['prefectures_id' => 7, 'name' => '稲敷市'],
            ['prefectures_id' => 7, 'name' => 'かすみがうら市'],
            ['prefectures_id' => 7, 'name' => '桜川市'],
            ['prefectures_id' => 7, 'name' => '神栖市'],
            ['prefectures_id' => 7, 'name' => '行方市'],
            ['prefectures_id' => 7, 'name' => '鉾田市'],
            ['prefectures_id' => 7, 'name' => 'つくばみらい市'],
            ['prefectures_id' => 7, 'name' => '小美玉市'],

            // 栃木県
            ['prefectures_id' => 8, 'name' => '宇都宮市'],
            ['prefectures_id' => 8, 'name' => '足利市'],
            ['prefectures_id' => 8, 'name' => '栃木市'],
            ['prefectures_id' => 8, 'name' => '佐野市'],
            ['prefectures_id' => 8, 'name' => '鹿沼市'],
            ['prefectures_id' => 8, 'name' => '日光市'],
            ['prefectures_id' => 8, 'name' => '小山市'],
            ['prefectures_id' => 8, 'name' => '真岡市'],
            ['prefectures_id' => 8, 'name' => '大田原市'],
            ['prefectures_id' => 8, 'name' => '矢板市'],
            ['prefectures_id' => 8, 'name' => '那須塩原市'],
            ['prefectures_id' => 8, 'name' => 'さくら市'],
            ['prefectures_id' => 8, 'name' => '那須烏山市'],
            ['prefectures_id' => 8, 'name' => '下野市'],

            // 群馬県
            ['prefectures_id' => 9, 'name' => '前橋市'],
            ['prefectures_id' => 9, 'name' => '高崎市'],
            ['prefectures_id' => 9, 'name' => '桐生市'],
            ['prefectures_id' => 9, 'name' => '伊勢崎市'],
            ['prefectures_id' => 9, 'name' => '太田市'],
            ['prefectures_id' => 9, 'name' => '沼田市'],
            ['prefectures_id' => 9, 'name' => '館林市'],
            ['prefectures_id' => 9, 'name' => '渋川市'],
            ['prefectures_id' => 9, 'name' => '藤岡市'],
            ['prefectures_id' => 9, 'name' => '富岡市'],
            ['prefectures_id' => 9, 'name' => '安中市'],
            ['prefectures_id' => 9, 'name' => 'みどり市'],

            // 埼玉県
            ['prefectures_id' => 10, 'name' => 'さいたま市'],
            ['prefectures_id' => 10, 'name' => '川越市'],
            ['prefectures_id' => 10, 'name' => '熊谷市'],
            ['prefectures_id' => 10, 'name' => '川口市'],
            ['prefectures_id' => 10, 'name' => '行田市'],
            ['prefectures_id' => 10, 'name' => '秩父市'],
            ['prefectures_id' => 10, 'name' => '所沢市'],
            ['prefectures_id' => 10, 'name' => '飯能市'],
            ['prefectures_id' => 10, 'name' => '加須市'],
            ['prefectures_id' => 10, 'name' => '本庄市'],
            ['prefectures_id' => 10, 'name' => '東松山市'],
            ['prefectures_id' => 10, 'name' => '春日部市'],
            ['prefectures_id' => 10, 'name' => '狭山市'],
            ['prefectures_id' => 10, 'name' => '羽生市'],
            ['prefectures_id' => 10, 'name' => '鴻巣市'],
            ['prefectures_id' => 10, 'name' => '深谷市'],
            ['prefectures_id' => 10, 'name' => '上尾市'],
            ['prefectures_id' => 10, 'name' => '草加市'],
            ['prefectures_id' => 10, 'name' => '越谷市'],
            ['prefectures_id' => 10, 'name' => '蕨市'],
            ['prefectures_id' => 10, 'name' => '戸田市'],
            ['prefectures_id' => 10, 'name' => '入間市'],
            ['prefectures_id' => 10, 'name' => '朝霞市'],
            ['prefectures_id' => 10, 'name' => '志木市'],
            ['prefectures_id' => 10, 'name' => '和光市'],
            ['prefectures_id' => 10, 'name' => '新座市'],
            ['prefectures_id' => 10, 'name' => '桶川市'],
            ['prefectures_id' => 10, 'name' => '久喜市'],
            ['prefectures_id' => 10, 'name' => '北本市'],
            ['prefectures_id' => 10, 'name' => '八潮市'],
            ['prefectures_id' => 10, 'name' => '富士見市'],
            ['prefectures_id' => 10, 'name' => '三郷市'],
            ['prefectures_id' => 10, 'name' => '蓮田市'],
            ['prefectures_id' => 10, 'name' => '坂戸市'],
            ['prefectures_id' => 10, 'name' => '幸手市'],
            ['prefectures_id' => 10, 'name' => '鶴ヶ島市'],
            ['prefectures_id' => 10, 'name' => '日高市'],
            ['prefectures_id' => 10, 'name' => '吉川市'],
            ['prefectures_id' => 10, 'name' => 'ふじみ野市'],
            ['prefectures_id' => 10, 'name' => '白岡市'],
            ['prefectures_id' => 11, 'name' => 'さいたま市'],
            ['prefectures_id' => 11, 'name' => '川越市'],
            ['prefectures_id' => 11, 'name' => '熊谷市'],
            ['prefectures_id' => 11, 'name' => '川口市'],
            ['prefectures_id' => 11, 'name' => '行田市'],
            ['prefectures_id' => 11, 'name' => '秩父市'],
            ['prefectures_id' => 11, 'name' => '所沢市'],
            ['prefectures_id' => 11, 'name' => '飯能市'],
            ['prefectures_id' => 11, 'name' => '加須市'],
            ['prefectures_id' => 11, 'name' => '本庄市'],
            ['prefectures_id' => 11, 'name' => '東松山市'],
            ['prefectures_id' => 11, 'name' => '春日部市'],
            ['prefectures_id' => 11, 'name' => '狭山市'],
            ['prefectures_id' => 11, 'name' => '羽生市'],
            ['prefectures_id' => 11, 'name' => '鴻巣市'],
            ['prefectures_id' => 11, 'name' => '深谷市'],
            ['prefectures_id' => 11, 'name' => '上尾市'],
            ['prefectures_id' => 11, 'name' => '草加市'],
            ['prefectures_id' => 11, 'name' => '越谷市'],
            ['prefectures_id' => 11, 'name' => '蕨市'],
            ['prefectures_id' => 11, 'name' => '戸田市'],
            ['prefectures_id' => 11, 'name' => '入間市'],
            ['prefectures_id' => 11, 'name' => '朝霞市'],
            ['prefectures_id' => 11, 'name' => '志木市'],
            ['prefectures_id' => 11, 'name' => '和光市'],
            ['prefectures_id' => 11, 'name' => '新座市'],
            ['prefectures_id' => 11, 'name' => '桶川市'],
            ['prefectures_id' => 11, 'name' => '久喜市'],
            ['prefectures_id' => 11, 'name' => '北本市'],
            ['prefectures_id' => 11, 'name' => '八潮市'],
            ['prefectures_id' => 11, 'name' => '富士見市'],
            ['prefectures_id' => 11, 'name' => '三郷市'],
            ['prefectures_id' => 11, 'name' => '蓮田市'],
            ['prefectures_id' => 11, 'name' => '坂戸市'],
            ['prefectures_id' => 11, 'name' => '幸手市'],
            ['prefectures_id' => 11, 'name' => '鶴ヶ島市'],
            ['prefectures_id' => 11, 'name' => '日高市'],
            ['prefectures_id' => 11, 'name' => '吉川市'],
            ['prefectures_id' => 11, 'name' => 'ふじみ野市'],
            ['prefectures_id' => 11, 'name' => '白岡市'],

            // 千葉県のデータ
            ['prefectures_id' => 12, 'name' => '千葉市'],
            ['prefectures_id' => 12, 'name' => '銚子市'],
            ['prefectures_id' => 12, 'name' => '市川市'],
            ['prefectures_id' => 12, 'name' => '船橋市'],
            ['prefectures_id' => 12, 'name' => '館山市'],
            ['prefectures_id' => 12, 'name' => '木更津市'],
            ['prefectures_id' => 12, 'name' => '松戸市'],
            ['prefectures_id' => 12, 'name' => '野田市'],
            ['prefectures_id' => 12, 'name' => '茂原市'],
            ['prefectures_id' => 12, 'name' => '成田市'],
            ['prefectures_id' => 12, 'name' => '佐倉市'],
            ['prefectures_id' => 12, 'name' => '東金市'],
            ['prefectures_id' => 12, 'name' => '旭市'],
            ['prefectures_id' => 12, 'name' => '習志野市'],
            ['prefectures_id' => 12, 'name' => '柏市'],
            ['prefectures_id' => 12, 'name' => '勝浦市'],
            ['prefectures_id' => 12, 'name' => '市原市'],
            ['prefectures_id' => 12, 'name' => '流山市'],
            ['prefectures_id' => 12, 'name' => '八千代市'],
            ['prefectures_id' => 12, 'name' => '我孫子市'],
            ['prefectures_id' => 12, 'name' => '鴨川市'],
            ['prefectures_id' => 12, 'name' => '鎌ケ谷市'],
            ['prefectures_id' => 12, 'name' => '君津市'],
            ['prefectures_id' => 12, 'name' => '富津市'],
            ['prefectures_id' => 12, 'name' => '浦安市'],
            ['prefectures_id' => 12, 'name' => '四街道市'],
            ['prefectures_id' => 12, 'name' => '袖ケ浦市'],
            ['prefectures_id' => 12, 'name' => '八街市'],
            ['prefectures_id' => 12, 'name' => '印西市'],
            ['prefectures_id' => 12, 'name' => '白井市'],
            ['prefectures_id' => 12, 'name' => '富里市'],
            ['prefectures_id' => 12, 'name' => '南房総市'],
            ['prefectures_id' => 12, 'name' => '匝瑳市'],
            ['prefectures_id' => 12, 'name' => '香取市'],
            ['prefectures_id' => 12, 'name' => '山武市'],
            ['prefectures_id' => 12, 'name' => 'いすみ市'],
            ['prefectures_id' => 12, 'name' => '大網白里市'],

            // 東京都のデータ
            ['prefectures_id' => 13, 'name' => '八王子市'],
            ['prefectures_id' => 13, 'name' => '立川市'],
            ['prefectures_id' => 13, 'name' => '武蔵野市'],
            ['prefectures_id' => 13, 'name' => '三鷹市'],
            ['prefectures_id' => 13, 'name' => '青梅市'],
            ['prefectures_id' => 13, 'name' => '府中市'],
            ['prefectures_id' => 13, 'name' => '昭島市'],
            ['prefectures_id' => 13, 'name' => '調布市'],
            ['prefectures_id' => 13, 'name' => '町田市'],
            ['prefectures_id' => 13, 'name' => '小金井市'],
            ['prefectures_id' => 13, 'name' => '小平市'],
            ['prefectures_id' => 13, 'name' => '日野市'],
            ['prefectures_id' => 13, 'name' => '東村山市'],
            ['prefectures_id' => 13, 'name' => '国分寺市'],
            ['prefectures_id' => 13, 'name' => '国立市'],
            ['prefectures_id' => 13, 'name' => '福生市'],
            ['prefectures_id' => 13, 'name' => '狛江市'],
            ['prefectures_id' => 13, 'name' => '東大和市'],
            ['prefectures_id' => 13, 'name' => '清瀬市'],
            ['prefectures_id' => 13, 'name' => '東久留米市'],
            ['prefectures_id' => 13, 'name' => '武蔵村山市'],
            ['prefectures_id' => 13, 'name' => '多摩市'],
            ['prefectures_id' => 13, 'name' => '稲城市'],
            ['prefectures_id' => 13, 'name' => '羽村市'],
            ['prefectures_id' => 13, 'name' => 'あきる野市'],
            ['prefectures_id' => 13, 'name' => '西東京市'],

            // 神奈川県のデータ
            ['prefectures_id' => 14, 'name' => '横浜市'],
            ['prefectures_id' => 14, 'name' => '川崎市'],
            ['prefectures_id' => 14, 'name' => '相模原市'],
            ['prefectures_id' => 14, 'name' => '横須賀市'],
            ['prefectures_id' => 14, 'name' => '平塚市'],
            ['prefectures_id' => 14, 'name' => '鎌倉市'],
            ['prefectures_id' => 14, 'name' => '藤沢市'],
            ['prefectures_id' => 14, 'name' => '小田原市'],
            ['prefectures_id' => 14, 'name' => '茅ヶ崎市'],
            ['prefectures_id' => 14, 'name' => '逗子市'],
            ['prefectures_id' => 14, 'name' => '三浦市'],
            ['prefectures_id' => 14, 'name' => '秦野市'],
            ['prefectures_id' => 14, 'name' => '厚木市'],
            ['prefectures_id' => 14, 'name' => '大和市'],
            ['prefectures_id' => 14, 'name' => '伊勢原市'],
            ['prefectures_id' => 14, 'name' => '海老名市'],
            ['prefectures_id' => 14, 'name' => '座間市'],
            ['prefectures_id' => 14, 'name' => '南足柄市'],
            ['prefectures_id' => 14, 'name' => '綾瀬市'],
            ['prefectures_id' => 15, 'name' => '新潟市'],
            ['prefectures_id' => 15, 'name' => '長岡市'],
            ['prefectures_id' => 15, 'name' => '三条市'],
            ['prefectures_id' => 15, 'name' => '柏崎市'],
            ['prefectures_id' => 15, 'name' => '新発田市'],
            ['prefectures_id' => 15, 'name' => '小千谷市'],
            ['prefectures_id' => 15, 'name' => '加茂市'],
            ['prefectures_id' => 15, 'name' => '十日町市'],
            ['prefectures_id' => 15, 'name' => '見附市'],
            ['prefectures_id' => 15, 'name' => '村上市'],
            ['prefectures_id' => 15, 'name' => '燕市'],
            ['prefectures_id' => 15, 'name' => '糸魚川市'],
            ['prefectures_id' => 15, 'name' => '妙高市'],
            ['prefectures_id' => 15, 'name' => '五泉市'],
            ['prefectures_id' => 15, 'name' => '上越市'],
            ['prefectures_id' => 15, 'name' => '佐渡市'],
            ['prefectures_id' => 15, 'name' => '魚沼市'],
            ['prefectures_id' => 15, 'name' => '南魚沼市'],
            ['prefectures_id' => 15, 'name' => '胎内市'],

            // 富山県（10市）
            ['prefectures_id' => 16, 'name' => '富山市'],
            ['prefectures_id' => 16, 'name' => '高岡市'],
            ['prefectures_id' => 16, 'name' => '魚津市'],
            ['prefectures_id' => 16, 'name' => '氷見市'],
            ['prefectures_id' => 16, 'name' => '滑川市'],
            ['prefectures_id' => 16, 'name' => '黒部市'],
            ['prefectures_id' => 16, 'name' => '砺波市'],
            ['prefectures_id' => 16, 'name' => '小矢部市'],
            ['prefectures_id' => 16, 'name' => '南砺市'],
            ['prefectures_id' => 16, 'name' => '射水市'],

            // 石川県（11市）
            ['prefectures_id' => 17, 'name' => '金沢市'],
            ['prefectures_id' => 17, 'name' => '七尾市'],
            ['prefectures_id' => 17, 'name' => '小松市'],
            ['prefectures_id' => 17, 'name' => '輪島市'],
            ['prefectures_id' => 17, 'name' => '珠洲市'],
            ['prefectures_id' => 17, 'name' => '加賀市'],
            ['prefectures_id' => 17, 'name' => '羽咋市'],
            ['prefectures_id' => 17, 'name' => 'かほく市'],
            ['prefectures_id' => 17, 'name' => '白山市'],
            ['prefectures_id' => 17, 'name' => '能美市'],
            ['prefectures_id' => 17, 'name' => '野々市市'],

            // 福井県（9市）
            ['prefectures_id' => 18, 'name' => '福井市'],
            ['prefectures_id' => 18, 'name' => '敦賀市'],
            ['prefectures_id' => 18, 'name' => '小浜市'],
            ['prefectures_id' => 18, 'name' => '大野市'],
            ['prefectures_id' => 18, 'name' => '勝山市'],
            ['prefectures_id' => 18, 'name' => '鯖江市'],
            ['prefectures_id' => 18, 'name' => 'あわら市'],
            ['prefectures_id' => 18, 'name' => '越前市'],
            ['prefectures_id' => 18, 'name' => '坂井市'],

            // 山梨県（13市）
            ['prefectures_id' => 19, 'name' => '甲府市'],
            ['prefectures_id' => 19, 'name' => '富士吉田市'],
            ['prefectures_id' => 19, 'name' => '都留市'],
            ['prefectures_id' => 19, 'name' => '山梨市'],
            ['prefectures_id' => 19, 'name' => '大月市'],
            ['prefectures_id' => 19, 'name' => '韮崎市'],
            ['prefectures_id' => 19, 'name' => '南アルプス市'],
            ['prefectures_id' => 19, 'name' => '北杜市'],
            ['prefectures_id' => 19, 'name' => '甲斐市'],
            ['prefectures_id' => 19, 'name' => '笛吹市'],
            ['prefectures_id' => 19, 'name' => '上野原市'],
            ['prefectures_id' => 19, 'name' => '甲州市'],
            ['prefectures_id' => 19, 'name' => '中央市'],
            //長野市
            ['prefectures_id' => 17, 'name' => '長野市'],
            ['prefectures_id' => 17, 'name' => '松本市'],
            ['prefectures_id' => 17, 'name' => '上田市'],
            ['prefectures_id' => 17, 'name' => '岡谷市'],
            ['prefectures_id' => 17, 'name' => '飯田市'],
            ['prefectures_id' => 17, 'name' => '諏訪市'],
            ['prefectures_id' => 17, 'name' => '須坂市'],
            ['prefectures_id' => 17, 'name' => '小諸市'],
            ['prefectures_id' => 17, 'name' => '伊那市'],
            ['prefectures_id' => 17, 'name' => '駒ヶ根市'],
            ['prefectures_id' => 17, 'name' => '中野市'],
            ['prefectures_id' => 17, 'name' => '大町市'],
            ['prefectures_id' => 17, 'name' => '飯山市'],
            ['prefectures_id' => 17, 'name' => '茅野市'],
            ['prefectures_id' => 17, 'name' => '塩尻市'],
            ['prefectures_id' => 17, 'name' => '佐久市'],
            ['prefectures_id' => 17, 'name' => '千曲市'],
            ['prefectures_id' => 17, 'name' => '東御市'],
            ['prefectures_id' => 17, 'name' => '安曇野市'],
            //岐阜市
            ['prefectures_id' => 18, 'name' => '岐阜市'],
            ['prefectures_id' => 18, 'name' => '大垣市'],
            ['prefectures_id' => 18, 'name' => '高山市'],
            ['prefectures_id' => 18, 'name' => '多治見市'],
            ['prefectures_id' => 18, 'name' => '関市'],
            ['prefectures_id' => 18, 'name' => '中津川市'],
            ['prefectures_id' => 18, 'name' => '美濃市'],
            ['prefectures_id' => 18, 'name' => '瑞浪市'],
            ['prefectures_id' => 18, 'name' => '羽島市'],
            ['prefectures_id' => 18, 'name' => '恵那市'],
            ['prefectures_id' => 18, 'name' => '美濃加茂市'],
            ['prefectures_id' => 18, 'name' => '土岐市'],
            ['prefectures_id' => 18, 'name' => '各務原市'],
            ['prefectures_id' => 18, 'name' => '可児市'],
            ['prefectures_id' => 18, 'name' => '山県市'],
            ['prefectures_id' => 18, 'name' => '瑞穂市'],
            ['prefectures_id' => 18, 'name' => '飛騨市'],
            ['prefectures_id' => 18, 'name' => '本巣市'],
            ['prefectures_id' => 18, 'name' => '郡上市'],
            ['prefectures_id' => 18, 'name' => '下呂市'],
            ['prefectures_id' => 18, 'name' => '海津市'],
            //静岡県
            ['prefectures_id' => 19, 'name' => '静岡市'],
            ['prefectures_id' => 19, 'name' => '浜松市'],
            ['prefectures_id' => 19, 'name' => '沼津市'],
            ['prefectures_id' => 19, 'name' => '熱海市'],
            ['prefectures_id' => 19, 'name' => '三島市'],
            ['prefectures_id' => 19, 'name' => '富士宮市'],
            ['prefectures_id' => 19, 'name' => '伊東市'],
            ['prefectures_id' => 19, 'name' => '島田市'],
            ['prefectures_id' => 19, 'name' => '富士市'],
            ['prefectures_id' => 19, 'name' => '磐田市'],
            ['prefectures_id' => 19, 'name' => '焼津市'],
            ['prefectures_id' => 19, 'name' => '掛川市'],
            ['prefectures_id' => 19, 'name' => '藤枝市'],
            ['prefectures_id' => 19, 'name' => '御殿場市'],
            ['prefectures_id' => 19, 'name' => '袋井市'],
            ['prefectures_id' => 19, 'name' => '下田市'],
            ['prefectures_id' => 19, 'name' => '裾野市'],
            ['prefectures_id' => 19, 'name' => '湖西市'],
            ['prefectures_id' => 19, 'name' => '伊豆市'],
            ['prefectures_id' => 19, 'name' => '御前崎市'],
            ['prefectures_id' => 19, 'name' => '菊川市'],
            ['prefectures_id' => 19, 'name' => '伊豆の国市'],
            ['prefectures_id' => 19, 'name' => '牧之原市'],
            //愛知県
            ['prefectures_id' => 20, 'name' => '名古屋市'],
            ['prefectures_id' => 20, 'name' => '豊橋市'],
            ['prefectures_id' => 20, 'name' => '岡崎市'],
            ['prefectures_id' => 20, 'name' => '一宮市'],
            ['prefectures_id' => 20, 'name' => '瀬戸市'],
            ['prefectures_id' => 20, 'name' => '半田市'],
            ['prefectures_id' => 20, 'name' => '春日井市'],
            ['prefectures_id' => 20, 'name' => '豊川市'],
            ['prefectures_id' => 20, 'name' => '津島市'],
            ['prefectures_id' => 20, 'name' => '碧南市'],
            ['prefectures_id' => 20, 'name' => '刈谷市'],
            ['prefectures_id' => 20, 'name' => '豊田市'],
            ['prefectures_id' => 20, 'name' => '安城市'],
            ['prefectures_id' => 20, 'name' => '西尾市'],
            ['prefectures_id' => 20, 'name' => '蒲郡市'],
            ['prefectures_id' => 20, 'name' => '犬山市'],
            ['prefectures_id' => 20, 'name' => '常滑市'],
            ['prefectures_id' => 20, 'name' => '江南市'],
            ['prefectures_id' => 20, 'name' => '小牧市'],
            ['prefectures_id' => 20, 'name' => '稲沢市'],
            ['prefectures_id' => 20, 'name' => '新城市'],
            ['prefectures_id' => 20, 'name' => '東海市'],
            ['prefectures_id' => 20, 'name' => '大府市'],
            ['prefectures_id' => 20, 'name' => '知多市'],
            ['prefectures_id' => 20, 'name' => '知立市'],
            ['prefectures_id' => 20, 'name' => '尾張旭市'],
            ['prefectures_id' => 20, 'name' => '高浜市'],
            ['prefectures_id' => 20, 'name' => '岩倉市'],
            ['prefectures_id' => 20, 'name' => '豊明市'],
            ['prefectures_id' => 20, 'name' => '日進市'],
            ['prefectures_id' => 20, 'name' => '田原市'],
            ['prefectures_id' => 20, 'name' => '愛西市'],
            ['prefectures_id' => 20, 'name' => '清須市'],
            ['prefectures_id' => 20, 'name' => '北名古屋市'],
            ['prefectures_id' => 20, 'name' => '弥富市'],
            ['prefectures_id' => 20, 'name' => 'みよし市'],
            ['prefectures_id' => 20, 'name' => 'あま市'],
            ['prefectures_id' => 20, 'name' => '長久手市'],
            //長野市
            ['prefectures_id' => 20, 'name' => '長野市'],
            ['prefectures_id' => 20, 'name' => '松本市'],
            ['prefectures_id' => 20, 'name' => '上田市'],
            ['prefectures_id' => 20, 'name' => '岡谷市'],
            ['prefectures_id' => 20, 'name' => '飯田市'],
            ['prefectures_id' => 20, 'name' => '諏訪市'],
            ['prefectures_id' => 20, 'name' => '須坂市'],
            ['prefectures_id' => 20, 'name' => '小諸市'],
            ['prefectures_id' => 20, 'name' => '伊那市'],
            ['prefectures_id' => 20, 'name' => '駒ヶ根市'],
            ['prefectures_id' => 20, 'name' => '中野市'],
            ['prefectures_id' => 20, 'name' => '大町市'],
            ['prefectures_id' => 20, 'name' => '飯山市'],
            ['prefectures_id' => 20, 'name' => '茅野市'],
            ['prefectures_id' => 20, 'name' => '塩尻市'],
            ['prefectures_id' => 20, 'name' => '佐久市'],
            ['prefectures_id' => 20, 'name' => '千曲市'],
            ['prefectures_id' => 20, 'name' => '東御市'],
            ['prefectures_id' => 20, 'name' => '安曇野市'],
            //岐阜市
            ['prefectures_id' => 21, 'name' => '岐阜市'],
            ['prefectures_id' => 21, 'name' => '大垣市'],
            ['prefectures_id' => 21, 'name' => '高山市'],
            ['prefectures_id' => 21, 'name' => '多治見市'],
            ['prefectures_id' => 21, 'name' => '関市'],
            ['prefectures_id' => 21, 'name' => '中津川市'],
            ['prefectures_id' => 21, 'name' => '美濃市'],
            ['prefectures_id' => 21, 'name' => '瑞浪市'],
            ['prefectures_id' => 21, 'name' => '羽島市'],
            ['prefectures_id' => 21, 'name' => '恵那市'],
            ['prefectures_id' => 21, 'name' => '美濃加茂市'],
            ['prefectures_id' => 21, 'name' => '土岐市'],
            ['prefectures_id' => 21, 'name' => '各務原市'],
            ['prefectures_id' => 21, 'name' => '可児市'],
            ['prefectures_id' => 21, 'name' => '山県市'],
            ['prefectures_id' => 21, 'name' => '瑞穂市'],
            ['prefectures_id' => 21, 'name' => '飛騨市'],
            ['prefectures_id' => 21, 'name' => '本巣市'],
            ['prefectures_id' => 21, 'name' => '郡上市'],
            ['prefectures_id' => 21, 'name' => '下呂市'],
            ['prefectures_id' => 21, 'name' => '海津市'],
            //静岡県
            ['prefectures_id' => 22, 'name' => '静岡市'],
            ['prefectures_id' => 22, 'name' => '浜松市'],
            ['prefectures_id' => 22, 'name' => '沼津市'],
            ['prefectures_id' => 22, 'name' => '熱海市'],
            ['prefectures_id' => 22, 'name' => '三島市'],
            ['prefectures_id' => 22, 'name' => '富士宮市'],
            ['prefectures_id' => 22, 'name' => '伊東市'],
            ['prefectures_id' => 22, 'name' => '島田市'],
            ['prefectures_id' => 22, 'name' => '富士市'],
            ['prefectures_id' => 22, 'name' => '磐田市'],
            ['prefectures_id' => 22, 'name' => '焼津市'],
            ['prefectures_id' => 22, 'name' => '掛川市'],
            ['prefectures_id' => 22, 'name' => '藤枝市'],
            ['prefectures_id' => 22, 'name' => '御殿場市'],
            ['prefectures_id' => 22, 'name' => '袋井市'],
            ['prefectures_id' => 22, 'name' => '下田市'],
            ['prefectures_id' => 22, 'name' => '裾野市'],
            ['prefectures_id' => 22, 'name' => '湖西市'],
            ['prefectures_id' => 22, 'name' => '伊豆市'],
            ['prefectures_id' => 22, 'name' => '御前崎市'],
            ['prefectures_id' => 22, 'name' => '菊川市'],
            ['prefectures_id' => 22, 'name' => '伊豆の国市'],
            ['prefectures_id' => 22, 'name' => '牧之原市'],
            //愛知県
            ['prefectures_id' => 23, 'name' => '名古屋市'],
            ['prefectures_id' => 23, 'name' => '豊橋市'],
            ['prefectures_id' => 23, 'name' => '岡崎市'],
            ['prefectures_id' => 23, 'name' => '一宮市'],
            ['prefectures_id' => 23, 'name' => '瀬戸市'],
            ['prefectures_id' => 23, 'name' => '半田市'],
            ['prefectures_id' => 23, 'name' => '春日井市'],
            ['prefectures_id' => 23, 'name' => '豊川市'],
            ['prefectures_id' => 23, 'name' => '津島市'],
            ['prefectures_id' => 23, 'name' => '碧南市'],
            ['prefectures_id' => 23, 'name' => '刈谷市'],
            ['prefectures_id' => 23, 'name' => '豊田市'],
            ['prefectures_id' => 23, 'name' => '安城市'],
            ['prefectures_id' => 23, 'name' => '西尾市'],
            ['prefectures_id' => 23, 'name' => '蒲郡市'],
            ['prefectures_id' => 23, 'name' => '犬山市'],
            ['prefectures_id' => 23, 'name' => '常滑市'],
            ['prefectures_id' => 23, 'name' => '江南市'],
            ['prefectures_id' => 23, 'name' => '小牧市'],
            ['prefectures_id' => 23, 'name' => '稲沢市'],
            ['prefectures_id' => 23, 'name' => '新城市'],
            ['prefectures_id' => 23, 'name' => '東海市'],
            ['prefectures_id' => 23, 'name' => '大府市'],
            ['prefectures_id' => 23, 'name' => '知多市'],
            ['prefectures_id' => 23, 'name' => '尾張旭市'],
            ['prefectures_id' => 23, 'name' => '高浜市'],
            ['prefectures_id' => 23, 'name' => '北名古屋市'],
            ['prefectures_id' => 23, 'name' => '長久手市'],
            ['prefectures_id' => 23, 'name' => '東浦町'],
            ['prefectures_id' => 23, 'name' => '大治町'],
            ['prefectures_id' => 23, 'name' => '蟹江町'],
            ['prefectures_id' => 23, 'name' => '飛島村'],
            ['prefectures_id' => 23, 'name' => '阿久比町'],
            ['prefectures_id' => 23, 'name' => '武豊町'],
            ['prefectures_id' => 23, 'name' => '幸田町'],
            ['prefectures_id' => 23, 'name' => '設楽町'],
            ['prefectures_id' => 23, 'name' => '東栄町'],
            ['prefectures_id' => 23, 'name' => '豊根村'],
            ['prefectures_id' => 24, 'name' => '津市'],
            ['prefectures_id' => 24, 'name' => '四日市市'],
            ['prefectures_id' => 24, 'name' => '伊勢市'],
            ['prefectures_id' => 24, 'name' => '松阪市'],
            ['prefectures_id' => 24, 'name' => '桑名市'],
            ['prefectures_id' => 24, 'name' => '鈴鹿市'],
            ['prefectures_id' => 24, 'name' => '名張市'],
            ['prefectures_id' => 24, 'name' => '尾鷲市'],
            ['prefectures_id' => 24, 'name' => '亀山市'],
            ['prefectures_id' => 24, 'name' => '鳥羽市'],
            ['prefectures_id' => 24, 'name' => '熊野市'],
            ['prefectures_id' => 24, 'name' => 'いなべ市'],
            ['prefectures_id' => 24, 'name' => '志摩市'],
            ['prefectures_id' => 24, 'name' => '伊賀市'],

            // 滋賀県
            ['prefectures_id' => 25, 'name' => '大津市'],
            ['prefectures_id' => 25, 'name' => '彦根市'],
            ['prefectures_id' => 25, 'name' => '長浜市'],
            ['prefectures_id' => 25, 'name' => '近江八幡市'],
            ['prefectures_id' => 25, 'name' => '草津市'],
            ['prefectures_id' => 25, 'name' => '守山市'],
            ['prefectures_id' => 25, 'name' => '栗東市'],
            ['prefectures_id' => 25, 'name' => '甲賀市'],
            ['prefectures_id' => 25, 'name' => '野洲市'],
            ['prefectures_id' => 25, 'name' => '湖南市'],
            ['prefectures_id' => 25, 'name' => '高島市'],
            ['prefectures_id' => 25, 'name' => '東近江市'],
            ['prefectures_id' => 25, 'name' => '米原市'],

            // 京都府
            ['prefectures_id' => 26, 'name' => '京都市'],
            ['prefectures_id' => 26, 'name' => '福知山市'],
            ['prefectures_id' => 26, 'name' => '舞鶴市'],
            ['prefectures_id' => 26, 'name' => '綾部市'],
            ['prefectures_id' => 26, 'name' => '宇治市'],
            ['prefectures_id' => 26, 'name' => '宮津市'],
            ['prefectures_id' => 26, 'name' => '亀岡市'],
            ['prefectures_id' => 26, 'name' => '城陽市'],
            ['prefectures_id' => 26, 'name' => '向日市'],
            ['prefectures_id' => 26, 'name' => '長岡京市'],
            ['prefectures_id' => 26, 'name' => '八幡市'],
            ['prefectures_id' => 26, 'name' => '京田辺市'],
            ['prefectures_id' => 26, 'name' => '京丹後市'],
            ['prefectures_id' => 26, 'name' => '南丹市'],
            ['prefectures_id' => 26, 'name' => '木津川市'],

            // 大阪府
            ['prefectures_id' => 27, 'name' => '大阪市'],
            ['prefectures_id' => 27, 'name' => '堺市'],
            ['prefectures_id' => 27, 'name' => '岸和田市'],
            ['prefectures_id' => 27, 'name' => '豊中市'],
            ['prefectures_id' => 27, 'name' => '池田市'],
            ['prefectures_id' => 27, 'name' => '吹田市'],
            ['prefectures_id' => 27, 'name' => '高槻市'],
            ['prefectures_id' => 27, 'name' => '貝塚市'],
            ['prefectures_id' => 27, 'name' => '守口市'],
            ['prefectures_id' => 27, 'name' => '枚方市'],
            ['prefectures_id' => 27, 'name' => '茨木市'],
            ['prefectures_id' => 27, 'name' => '八尾市'],
            ['prefectures_id' => 27, 'name' => '泉大津市'],
            ['prefectures_id' => 27, 'name' => '富田林市'],
            ['prefectures_id' => 27, 'name' => '寝屋川市'],
            ['prefectures_id' => 27, 'name' => '河内長野市'],
            ['prefectures_id' => 27, 'name' => '松原市'],
            ['prefectures_id' => 27, 'name' => '大東市'],
            ['prefectures_id' => 27, 'name' => '和泉市'],
            ['prefectures_id' => 27, 'name' => '箕面市'],
            ['prefectures_id' => 27, 'name' => '柏原市'],
            ['prefectures_id' => 27, 'name' => '羽曳野市'],
            ['prefectures_id' => 27, 'name' => '門真市'],
            ['prefectures_id' => 27, 'name' => '摂津市'],
            ['prefectures_id' => 27, 'name' => '高石市'],
            ['prefectures_id' => 27, 'name' => '藤井寺市'],
            ['prefectures_id' => 27, 'name' => '東大阪市'],
            ['prefectures_id' => 27, 'name' => '泉佐野市'],
            ['prefectures_id' => 27, 'name' => '富田林市'],
            ['prefectures_id' => 27, 'name' => '泉南市'],
            ['prefectures_id' => 27, 'name' => '四條畷市'],
            ['prefectures_id' => 27, 'name' => '交野市'],
            ['prefectures_id' => 27, 'name' => '大阪狭山市'],
            ['prefectures_id' => 27, 'name' => '阪南市'],

            // 兵庫県
            ['prefectures_id' => 28, 'name' => '神戸市'],
            ['prefectures_id' => 28, 'name' => '姫路市'],
            ['prefectures_id' => 28, 'name' => '尼崎市'],
            ['prefectures_id' => 28, 'name' => '西宮市'],
            ['prefectures_id' => 28, 'name' => '明石市'],
            ['prefectures_id' => 28, 'name' => '洲本市'],
            ['prefectures_id' => 28, 'name' => '相生市'],
            ['prefectures_id' => 28, 'name' => '豊岡市'],
            ['prefectures_id' => 28, 'name' => '加古川市'],
            ['prefectures_id' => 28, 'name' => '赤穂市'],
            ['prefectures_id' => 28, 'name' => '西脇市'],
            ['prefectures_id' => 28, 'name' => '宝塚市'],
            ['prefectures_id' => 28, 'name' => '三木市'],
            ['prefectures_id' => 28, 'name' => '高砂市'],
            ['prefectures_id' => 28, 'name' => '川西市'],
            ['prefectures_id' => 28, 'name' => '小野市'],
            ['prefectures_id' => 28, 'name' => '三田市'],
            ['prefectures_id' => 28, 'name' => '加西市'],
            ['prefectures_id' => 28, 'name' => '篠山市'],
            ['prefectures_id' => 28, 'name' => '養父市'],
            ['prefectures_id' => 28, 'name' => '丹波市'],
            ['prefectures_id' => 28, 'name' => '南あわじ市'],
            ['prefectures_id' => 28, 'name' => '朝来市'],
            ['prefectures_id' => 28, 'name' => '淡路市'],
            ['prefectures_id' => 28, 'name' => '宍粟市'],
            ['prefectures_id' => 28, 'name' => 'たつの市'],
            ['prefectures_id' => 28, 'name' => '猪名川町'],
            ['prefectures_id' => 28, 'name' => '稲美町'],
            ['prefectures_id' => 28, 'name' => '播磨町'],

            // 奈良県
            ['prefectures_id' => 29, 'name' => '奈良市'],
            ['prefectures_id' => 29, 'name' => '大和高田市'],
            ['prefectures_id' => 29, 'name' => '大和郡山市'],
            ['prefectures_id' => 29, 'name' => '天理市'],
            ['prefectures_id' => 29, 'name' => '橿原市'],
            ['prefectures_id' => 29, 'name' => '桜井市'],
            ['prefectures_id' => 29, 'name' => '五條市'],
            ['prefectures_id' => 29, 'name' => '御所市'],
            ['prefectures_id' => 29, 'name' => '生駒市'],
            ['prefectures_id' => 29, 'name' => '香芝市'],
            ['prefectures_id' => 29, 'name' => '葛城市'],
            ['prefectures_id' => 29, 'name' => '宇陀市'],

            // 和歌山県
            ['prefectures_id' => 30, 'name' => '和歌山市'],
            ['prefectures_id' => 30, 'name' => '海南市'],
            ['prefectures_id' => 30, 'name' => '橋本市'],
            ['prefectures_id' => 30, 'name' => '有田市'],
            ['prefectures_id' => 30, 'name' => '御坊市'],
            ['prefectures_id' => 30, 'name' => '田辺市'],
            ['prefectures_id' => 30, 'name' => '新宮市'],
            ['prefectures_id' => 30, 'name' => '紀の川市'],
            ['prefectures_id' => 30, 'name' => '岩出市'],
            // 鳥取県
            ['prefectures_id' => 31, 'name' => '鳥取市'],
            ['prefectures_id' => 31, 'name' => '米子市'],
            ['prefectures_id' => 31, 'name' => '倉吉市'],
            ['prefectures_id' => 31, 'name' => '境港市'],

            // 島根県
            ['prefectures_id' => 32, 'name' => '松江市'],
            ['prefectures_id' => 32, 'name' => '浜田市'],
            ['prefectures_id' => 32, 'name' => '出雲市'],
            ['prefectures_id' => 32, 'name' => '益田市'],
            ['prefectures_id' => 32, 'name' => '大田市'],
            ['prefectures_id' => 32, 'name' => '安来市'],
            ['prefectures_id' => 32, 'name' => '江津市'],
            ['prefectures_id' => 32, 'name' => '雲南市'],

            // 岡山県
            ['prefectures_id' => 33, 'name' => '岡山市'],
            ['prefectures_id' => 33, 'name' => '倉敷市'],
            ['prefectures_id' => 33, 'name' => '津山市'],
            ['prefectures_id' => 33, 'name' => '玉野市'],
            ['prefectures_id' => 33, 'name' => '笠岡市'],
            ['prefectures_id' => 33, 'name' => '井原市'],
            ['prefectures_id' => 33, 'name' => '総社市'],
            ['prefectures_id' => 33, 'name' => '高梁市'],
            ['prefectures_id' => 33, 'name' => '新見市'],
            ['prefectures_id' => 33, 'name' => '備前市'],
            ['prefectures_id' => 33, 'name' => '瀬戸内市'],
            ['prefectures_id' => 33, 'name' => '赤磐市'],
            ['prefectures_id' => 33, 'name' => '真庭市'],
            ['prefectures_id' => 33, 'name' => '美作市'],
            ['prefectures_id' => 33, 'name' => '浅口市'],

            // 広島県
            ['prefectures_id' => 34, 'name' => '広島市'],
            ['prefectures_id' => 34, 'name' => '呉市'],
            ['prefectures_id' => 34, 'name' => '竹原市'],
            ['prefectures_id' => 34, 'name' => '三原市'],
            ['prefectures_id' => 34, 'name' => '尾道市'],
            ['prefectures_id' => 34, 'name' => '福山市'],
            ['prefectures_id' => 34, 'name' => '府中市'],
            ['prefectures_id' => 34, 'name' => '三次市'],
            ['prefectures_id' => 34, 'name' => '庄原市'],
            ['prefectures_id' => 34, 'name' => '大竹市'],
            ['prefectures_id' => 34, 'name' => '東広島市'],
            ['prefectures_id' => 34, 'name' => '廿日市市'],
            ['prefectures_id' => 34, 'name' => '安芸高田市'],
            ['prefectures_id' => 34, 'name' => '江田島市'],

            // 山口県
            ['prefectures_id' => 35, 'name' => '下関市'],
            ['prefectures_id' => 35, 'name' => '宇部市'],
            ['prefectures_id' => 35, 'name' => '山口市'],
            ['prefectures_id' => 35, 'name' => '萩市'],
            ['prefectures_id' => 35, 'name' => '防府市'],
            ['prefectures_id' => 35, 'name' => '下松市'],
            ['prefectures_id' => 35, 'name' => '岩国市'],
            ['prefectures_id' => 35, 'name' => '光市'],
            ['prefectures_id' => 35, 'name' => '長門市'],
            ['prefectures_id' => 35, 'name' => '柳井市'],
            ['prefectures_id' => 35, 'name' => '美祢市'],
            ['prefectures_id' => 35, 'name' => '周南市'],
            ['prefectures_id' => 35, 'name' => '山陽小野田市'],
            // 徳島県
            ['prefectures_id' => 36, 'name' => '徳島市'],
            ['prefectures_id' => 36, 'name' => '鳴門市'],
            ['prefectures_id' => 36, 'name' => '小松島市'],
            ['prefectures_id' => 36, 'name' => '阿南市'],
            ['prefectures_id' => 36, 'name' => '吉野川市'],
            ['prefectures_id' => 36, 'name' => '阿波市'],
            ['prefectures_id' => 36, 'name' => '美馬市'],
            ['prefectures_id' => 36, 'name' => '三好市'],

            // 香川県
            ['prefectures_id' => 37, 'name' => '高松市'],
            ['prefectures_id' => 37, 'name' => '丸亀市'],
            ['prefectures_id' => 37, 'name' => '坂出市'],
            ['prefectures_id' => 37, 'name' => '善通寺市'],
            ['prefectures_id' => 37, 'name' => '観音寺市'],
            ['prefectures_id' => 37, 'name' => 'さぬき市'],
            ['prefectures_id' => 37, 'name' => '東かがわ市'],
            ['prefectures_id' => 37, 'name' => '三豊市'],

            // 愛媛県
            ['prefectures_id' => 38, 'name' => '松山市'],
            ['prefectures_id' => 38, 'name' => '今治市'],
            ['prefectures_id' => 38, 'name' => '宇和島市'],
            ['prefectures_id' => 38, 'name' => '八幡浜市'],
            ['prefectures_id' => 38, 'name' => '新居浜市'],
            ['prefectures_id' => 38, 'name' => '西条市'],
            ['prefectures_id' => 38, 'name' => '大洲市'],
            ['prefectures_id' => 38, 'name' => '伊予市'],
            ['prefectures_id' => 38, 'name' => '四国中央市'],
            ['prefectures_id' => 38, 'name' => '西予市'],
            ['prefectures_id' => 38, 'name' => '東温市'],

            // 高知県
            ['prefectures_id' => 39, 'name' => '高知市'],
            ['prefectures_id' => 39, 'name' => '室戸市'],
            ['prefectures_id' => 39, 'name' => '安芸市'],
            ['prefectures_id' => 39, 'name' => '南国市'],
            ['prefectures_id' => 39, 'name' => '土佐市'],
            ['prefectures_id' => 39, 'name' => '須崎市'],
            ['prefectures_id' => 39, 'name' => '宿毛市'],
            ['prefectures_id' => 39, 'name' => '土佐清水市'],
            ['prefectures_id' => 39, 'name' => '四万十市'],
            ['prefectures_id' => 39, 'name' => '香南市'],
            ['prefectures_id' => 39, 'name' => '香美市'],
            // 福岡県
            ['prefectures_id' => 40, 'name' => '福岡市'],
            ['prefectures_id' => 40, 'name' => '北九州市'],
            ['prefectures_id' => 40, 'name' => '大牟田市'],
            ['prefectures_id' => 40, 'name' => '久留米市'],
            ['prefectures_id' => 40, 'name' => '直方市'],
            ['prefectures_id' => 40, 'name' => '飯塚市'],
            ['prefectures_id' => 40, 'name' => '田川市'],
            ['prefectures_id' => 40, 'name' => '柳川市'],
            ['prefectures_id' => 40, 'name' => '八女市'],
            ['prefectures_id' => 40, 'name' => '筑後市'],
            ['prefectures_id' => 40, 'name' => '大川市'],
            ['prefectures_id' => 40, 'name' => '行橋市'],
            ['prefectures_id' => 40, 'name' => '豊前市'],
            ['prefectures_id' => 40, 'name' => '中間市'],
            ['prefectures_id' => 40, 'name' => '小郡市'],
            ['prefectures_id' => 40, 'name' => '筑紫野市'],
            ['prefectures_id' => 40, 'name' => '春日市'],
            ['prefectures_id' => 40, 'name' => '大野城市'],
            ['prefectures_id' => 40, 'name' => '宗像市'],
            ['prefectures_id' => 40, 'name' => '太宰府市'],
            ['prefectures_id' => 40, 'name' => '古賀市'],
            ['prefectures_id' => 40, 'name' => '福津市'],
            ['prefectures_id' => 40, 'name' => 'うきは市'],
            ['prefectures_id' => 40, 'name' => '宮若市'],
            ['prefectures_id' => 40, 'name' => '嘉麻市'],
            ['prefectures_id' => 40, 'name' => '朝倉市'],
            ['prefectures_id' => 40, 'name' => 'みやま市'],
            ['prefectures_id' => 40, 'name' => '糸島市'],
            ['prefectures_id' => 40, 'name' => '那珂川市'],

            // 佐賀県
            ['prefectures_id' => 41, 'name' => '佐賀市'],
            ['prefectures_id' => 41, 'name' => '唐津市'],
            ['prefectures_id' => 41, 'name' => '鳥栖市'],
            ['prefectures_id' => 41, 'name' => '多久市'],
            ['prefectures_id' => 41, 'name' => '伊万里市'],
            ['prefectures_id' => 41, 'name' => '武雄市'],
            ['prefectures_id' => 41, 'name' => '鹿島市'],
            ['prefectures_id' => 41, 'name' => '小城市'],
            ['prefectures_id' => 41, 'name' => '嬉野市'],
            ['prefectures_id' => 41, 'name' => '神埼市'],

            //長崎県
            ['prefectures_id' => 42, 'name' => '長崎市'],
            ['prefectures_id' => 42, 'name' => '佐世保市'],
            ['prefectures_id' => 42, 'name' => '島原市'],
            ['prefectures_id' => 42, 'name' => '諫早市'],
            ['prefectures_id' => 42, 'name' => '大村市'],
            ['prefectures_id' => 42, 'name' => '平戸市'],
            ['prefectures_id' => 42, 'name' => '松浦市'],
            ['prefectures_id' => 42, 'name' => '対馬市'],
            ['prefectures_id' => 42, 'name' => '壱岐市'],
            ['prefectures_id' => 42, 'name' => '五島市'],
            ['prefectures_id' => 42, 'name' => '西海市'],
            ['prefectures_id' => 42, 'name' => '雲仙市'],
            ['prefectures_id' => 42, 'name' => '南島原市'],

            //熊本県
            ['prefectures_id' => 43, 'name' => '熊本市'],
            ['prefectures_id' => 43, 'name' => '八代市'],
            ['prefectures_id' => 43, 'name' => '人吉市'],
            ['prefectures_id' => 43, 'name' => '荒尾市'],
            ['prefectures_id' => 43, 'name' => '水俣市'],
            ['prefectures_id' => 43, 'name' => '玉名市'],
            ['prefectures_id' => 43, 'name' => '山鹿市'],
            ['prefectures_id' => 43, 'name' => '菊池市'],
            ['prefectures_id' => 43, 'name' => '宇土市'],
            ['prefectures_id' => 43, 'name' => '上天草市'],
            ['prefectures_id' => 43, 'name' => '宇城市'],
            ['prefectures_id' => 43, 'name' => '阿蘇市'],
            ['prefectures_id' => 43, 'name' => '天草市'],
            ['prefectures_id' => 43, 'name' => '合志市'],
            //大分県
            ['prefectures_id' => 44, 'name' => '大分市'],
            ['prefectures_id' => 44, 'name' => '別府市'],
            ['prefectures_id' => 44, 'name' => '中津市'],
            ['prefectures_id' => 44, 'name' => '日田市'],
            ['prefectures_id' => 44, 'name' => '佐伯市'],
            ['prefectures_id' => 44, 'name' => '臼杵市'],
            ['prefectures_id' => 44, 'name' => '津久見市'],
            ['prefectures_id' => 44, 'name' => '竹田市'],
            ['prefectures_id' => 44, 'name' => '豊後高田市'],
            ['prefectures_id' => 44, 'name' => '杵築市'],
            ['prefectures_id' => 44, 'name' => '宇佐市'],
            ['prefectures_id' => 44, 'name' => '豊後大野市'],
            ['prefectures_id' => 44, 'name' => '由布市'],
            ['prefectures_id' => 44, 'name' => '国東市'],
            //宮崎県
            ['prefectures_id' => 45, 'name' => '宮崎市'],
            ['prefectures_id' => 45, 'name' => '都城市'],
            ['prefectures_id' => 45, 'name' => '延岡市'],
            ['prefectures_id' => 45, 'name' => '日南市'],
            ['prefectures_id' => 45, 'name' => '小林市'],
            ['prefectures_id' => 45, 'name' => '日向市'],
            ['prefectures_id' => 45, 'name' => '串間市'],
            ['prefectures_id' => 45, 'name' => '西都市'],
            ['prefectures_id' => 45, 'name' => 'えびの市'],
            //鹿児島県
            ['prefectures_id' => 46, 'name' => '鹿児島市'],
            ['prefectures_id' => 46, 'name' => '鹿屋市'],
            ['prefectures_id' => 46, 'name' => '枕崎市'],
            ['prefectures_id' => 46, 'name' => '阿久根市'],
            ['prefectures_id' => 46, 'name' => '出水市'],
            ['prefectures_id' => 46, 'name' => '大口市'],
            ['prefectures_id' => 46, 'name' => '指宿市'],
            ['prefectures_id' => 46, 'name' => '西之表市'],
            ['prefectures_id' => 46, 'name' => '垂水市'],
            ['prefectures_id' => 46, 'name' => '薩摩川内市'],
            ['prefectures_id' => 46, 'name' => '日置市'],
            ['prefectures_id' => 46, 'name' => '曽於市'],
            ['prefectures_id' => 46, 'name' => '霧島市'],
            ['prefectures_id' => 46, 'name' => 'いちき串木野市'],
            ['prefectures_id' => 46, 'name' => '南さつま市'],
            ['prefectures_id' => 46, 'name' => '志布志市'],
            ['prefectures_id' => 46, 'name' => '奄美市'],
            ['prefectures_id' => 46, 'name' => '南九州市'],
            ['prefectures_id' => 46, 'name' => '伊佐市'],
            //沖縄県
            ['prefectures_id' => 47, 'name' => '那覇市'],
            ['prefectures_id' => 47, 'name' => '宜野湾市'],
            ['prefectures_id' => 47, 'name' => '石垣市'],
            ['prefectures_id' => 47, 'name' => '浦添市'],
            ['prefectures_id' => 47, 'name' => '名護市'],
            ['prefectures_id' => 47, 'name' => '糸満市'],
            ['prefectures_id' => 47, 'name' => '沖縄市'],
            ['prefectures_id' => 47, 'name' => '豊見城市'],
            ['prefectures_id' => 47, 'name' => 'うるま市'],
            ['prefectures_id' => 47, 'name' => '宮古島市'],
            ['prefectures_id' => 47, 'name' => '南城市'],
        ];

        foreach ($citys as  $city) {
            DB::table('cities')->insert($city);
        }
    }
}
