<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("cities")->truncate();
        $cities = [
            // 都道府県ID 1: 北海道
            ["prefecture_id" => 1, "name" => "札幌市"],
            ["prefecture_id" => 1, "name" => "函館市"],
            ["prefecture_id" => 1, "name" => "小樽市"],
            ["prefecture_id" => 1, "name" => "旭川市"],
            ["prefecture_id" => 1, "name" => "室蘭市"],
            ["prefecture_id" => 1, "name" => "釧路市"],
            ["prefecture_id" => 1, "name" => "帯広市"],
            ["prefecture_id" => 1, "name" => "北見市"],
            ["prefecture_id" => 1, "name" => "夕張市"],
            ["prefecture_id" => 1, "name" => "岩見沢市"],
            ["prefecture_id" => 1, "name" => "網走市"],
            ["prefecture_id" => 1, "name" => "留萌市"],
            ["prefecture_id" => 1, "name" => "苫小牧市"],
            ["prefecture_id" => 1, "name" => "稚内市"],
            ["prefecture_id" => 1, "name" => "美唄市"],
            ["prefecture_id" => 1, "name" => "芦別市"],
            ["prefecture_id" => 1, "name" => "江別市"],
            ["prefecture_id" => 1, "name" => "赤平市"],
            ["prefecture_id" => 1, "name" => "紋別市"],
            ["prefecture_id" => 1, "name" => "士別市"],
            ["prefecture_id" => 1, "name" => "名寄市"],
            ["prefecture_id" => 1, "name" => "三笠市"],
            ["prefecture_id" => 1, "name" => "千歳市"],
            ["prefecture_id" => 1, "name" => "滝川市"],
            ["prefecture_id" => 1, "name" => "砂川市"],
            ["prefecture_id" => 1, "name" => "歌志内市"],
            ["prefecture_id" => 1, "name" => "深川市"],
            ["prefecture_id" => 1, "name" => "富良野市"],
            ["prefecture_id" => 1, "name" => "登別市"],
            ["prefecture_id" => 1, "name" => "恵庭市"],
            ["prefecture_id" => 1, "name" => "伊達市"],
            ["prefecture_id" => 1, "name" => "北広島市"],
            ["prefecture_id" => 1, "name" => "石狩市"],
            ["prefecture_id" => 1, "name" => "北斗市"],

            // 都道府県ID 2: 青森県
            ["prefecture_id" => 2, "name" => "青森市"],
            ["prefecture_id" => 2, "name" => "弘前市"],
            ["prefecture_id" => 2, "name" => "八戸市"],
            ["prefecture_id" => 2, "name" => "黒石市"],
            ["prefecture_id" => 2, "name" => "五所川原市"],
            ["prefecture_id" => 2, "name" => "十和田市"],
            ["prefecture_id" => 2, "name" => "三沢市"],
            ["prefecture_id" => 2, "name" => "むつ市"],
            ["prefecture_id" => 2, "name" => "つがる市"],
            ["prefecture_id" => 2, "name" => "平川市"],

            // 都道府県ID 3: 岩手県
            ["prefecture_id" => 3, "name" => "盛岡市"],
            ["prefecture_id" => 3, "name" => "宮古市"],
            ["prefecture_id" => 3, "name" => "大船渡市"],
            ["prefecture_id" => 3, "name" => "花巻市"],
            ["prefecture_id" => 3, "name" => "北上市"],
            ["prefecture_id" => 3, "name" => "久慈市"],
            ["prefecture_id" => 3, "name" => "遠野市"],
            ["prefecture_id" => 3, "name" => "一関市"],
            ["prefecture_id" => 3, "name" => "陸前高田市"],
            ["prefecture_id" => 3, "name" => "釜石市"],
            ["prefecture_id" => 3, "name" => "二戸市"],
            ["prefecture_id" => 3, "name" => "八幡平市"],
            ["prefecture_id" => 3, "name" => "奥州市"],
            ["prefecture_id" => 3, "name" => "滝沢市"],

            // 都道府県ID 4: 宮城県
            ["prefecture_id" => 4, "name" => "仙台市"],
            ["prefecture_id" => 4, "name" => "石巻市"],
            ["prefecture_id" => 4, "name" => "塩竈市"],
            ["prefecture_id" => 4, "name" => "気仙沼市"],
            ["prefecture_id" => 4, "name" => "白石市"],
            ["prefecture_id" => 4, "name" => "名取市"],
            ["prefecture_id" => 4, "name" => "角田市"],
            ["prefecture_id" => 4, "name" => "多賀城市"],
            ["prefecture_id" => 4, "name" => "岩沼市"],
            ["prefecture_id" => 4, "name" => "登米市"],
            ["prefecture_id" => 4, "name" => "栗原市"],
            ["prefecture_id" => 4, "name" => "東松島市"],
            ["prefecture_id" => 4, "name" => "大崎市"],
            ["prefecture_id" => 4, "name" => "富谷市"],

            // 都道府県ID 5: 秋田県
            ["prefecture_id" => 5, "name" => "秋田市"],
            ["prefecture_id" => 5, "name" => "能代市"],
            ["prefecture_id" => 5, "name" => "横手市"],
            ["prefecture_id" => 5, "name" => "大館市"],
            ["prefecture_id" => 5, "name" => "男鹿市"],
            ["prefecture_id" => 5, "name" => "湯沢市"],
            ["prefecture_id" => 5, "name" => "鹿角市"],
            ["prefecture_id" => 5, "name" => "由利本荘市"],
            ["prefecture_id" => 5, "name" => "潟上市"],
            ["prefecture_id" => 5, "name" => "大仙市"],
            ["prefecture_id" => 5, "name" => "北秋田市"],
            ["prefecture_id" => 5, "name" => "にかほ市"],
            ["prefecture_id" => 5, "name" => "仙北市"],

            // 都道府県ID 6: 山形県
            ["prefecture_id" => 6, "name" => "山形市"],
            ["prefecture_id" => 6, "name" => "米沢市"],
            ["prefecture_id" => 6, "name" => "鶴岡市"],
            ["prefecture_id" => 6, "name" => "酒田市"],
            ["prefecture_id" => 6, "name" => "新庄市"],
            ["prefecture_id" => 6, "name" => "寒河江市"],
            ["prefecture_id" => 6, "name" => "上山市"],
            ["prefecture_id" => 6, "name" => "村山市"],
            ["prefecture_id" => 6, "name" => "長井市"],
            ["prefecture_id" => 6, "name" => "天童市"],
            ["prefecture_id" => 6, "name" => "東根市"],
            ["prefecture_id" => 6, "name" => "尾花沢市"],
            ["prefecture_id" => 6, "name" => "南陽市"],

            // 都道府県ID 7: 福島県
            ["prefecture_id" => 7, "name" => "福島市"],
            ["prefecture_id" => 7, "name" => "会津若松市"],
            ["prefecture_id" => 7, "name" => "郡山市"],
            ["prefecture_id" => 7, "name" => "いわき市"],
            ["prefecture_id" => 7, "name" => "白河市"],
            ["prefecture_id" => 7, "name" => "須賀川市"],
            ["prefecture_id" => 7, "name" => "喜多方市"],
            ["prefecture_id" => 7, "name" => "相馬市"],
            ["prefecture_id" => 7, "name" => "二本松市"],
            ["prefecture_id" => 7, "name" => "田村市"],
            ["prefecture_id" => 7, "name" => "南相馬市"],
            ["prefecture_id" => 7, "name" => "伊達市"],
            ["prefecture_id" => 7, "name" => "本宮市"],

            // 都道府県ID 8: 茨城県
            ["prefecture_id" => 8, "name" => "水戸市"],
            ["prefecture_id" => 8, "name" => "日立市"],
            ["prefecture_id" => 8, "name" => "土浦市"],
            ["prefecture_id" => 8, "name" => "古河市"],
            ["prefecture_id" => 8, "name" => "石岡市"],
            ["prefecture_id" => 8, "name" => "結城市"],
            ["prefecture_id" => 8, "name" => "龍ケ崎市"],
            ["prefecture_id" => 8, "name" => "下妻市"],
            ["prefecture_id" => 8, "name" => "常総市"],
            ["prefecture_id" => 8, "name" => "常陸太田市"],
            ["prefecture_id" => 8, "name" => "高萩市"],
            ["prefecture_id" => 8, "name" => "北茨城市"],
            ["prefecture_id" => 8, "name" => "笠間市"],
            ["prefecture_id" => 8, "name" => "取手市"],
            ["prefecture_id" => 8, "name" => "牛久市"],
            ["prefecture_id" => 8, "name" => "つくば市"],
            ["prefecture_id" => 8, "name" => "ひたちなか市"],
            ["prefecture_id" => 8, "name" => "鹿嶋市"],
            ["prefecture_id" => 8, "name" => "潮来市"],
            ["prefecture_id" => 8, "name" => "守谷市"],
            ["prefecture_id" => 8, "name" => "常陸大宮市"],
            ["prefecture_id" => 8, "name" => "那珂市"],
            ["prefecture_id" => 8, "name" => "筑西市"],
            ["prefecture_id" => 8, "name" => "坂東市"],
            ["prefecture_id" => 8, "name" => "稲敷市"],
            ["prefecture_id" => 8, "name" => "かすみがうら市"],
            ["prefecture_id" => 8, "name" => "桜川市"],
            ["prefecture_id" => 8, "name" => "神栖市"],
            ["prefecture_id" => 8, "name" => "行方市"],
            ["prefecture_id" => 8, "name" => "鉾田市"],
            ["prefecture_id" => 8, "name" => "つくばみらい市"],
            ["prefecture_id" => 8, "name" => "小美玉市"],

            // 都道府県ID 9: 栃木県
            ["prefecture_id" => 9, "name" => "宇都宮市"],
            ["prefecture_id" => 9, "name" => "足利市"],
            ["prefecture_id" => 9, "name" => "栃木市"],
            ["prefecture_id" => 9, "name" => "佐野市"],
            ["prefecture_id" => 9, "name" => "鹿沼市"],
            ["prefecture_id" => 9, "name" => "日光市"],
            ["prefecture_id" => 9, "name" => "小山市"],
            ["prefecture_id" => 9, "name" => "真岡市"],
            ["prefecture_id" => 9, "name" => "大田原市"],
            ["prefecture_id" => 9, "name" => "矢板市"],
            ["prefecture_id" => 9, "name" => "那須塩原市"],
            ["prefecture_id" => 9, "name" => "さくら市"],
            ["prefecture_id" => 9, "name" => "那須烏山市"],
            ["prefecture_id" => 9, "name" => "下野市"],

            // 都道府県ID 10: 群馬県
            ["prefecture_id" => 10, "name" => "前橋市"],
            ["prefecture_id" => 10, "name" => "高崎市"],
            ["prefecture_id" => 10, "name" => "桐生市"],
            ["prefecture_id" => 10, "name" => "伊勢崎市"],
            ["prefecture_id" => 10, "name" => "太田市"],
            ["prefecture_id" => 10, "name" => "沼田市"],
            ["prefecture_id" => 10, "name" => "館林市"],
            ["prefecture_id" => 10, "name" => "渋川市"],
            ["prefecture_id" => 10, "name" => "藤岡市"],
            ["prefecture_id" => 10, "name" => "富岡市"],
            ["prefecture_id" => 10, "name" => "安中市"],
            ["prefecture_id" => 10, "name" => "みどり市"],

            // 都道府県ID 11: 埼玉県
            ["prefecture_id" => 11, "name" => "さいたま市"],
            ["prefecture_id" => 11, "name" => "川越市"],
            ["prefecture_id" => 11, "name" => "熊谷市"],
            ["prefecture_id" => 11, "name" => "川口市"],
            ["prefecture_id" => 11, "name" => "行田市"],
            ["prefecture_id" => 11, "name" => "秩父市"],
            ["prefecture_id" => 11, "name" => "所沢市"],
            ["prefecture_id" => 11, "name" => "飯能市"],
            ["prefecture_id" => 11, "name" => "加須市"],
            ["prefecture_id" => 11, "name" => "本庄市"],
            ["prefecture_id" => 11, "name" => "東松山市"],
            ["prefecture_id" => 11, "name" => "春日部市"],
            ["prefecture_id" => 11, "name" => "狭山市"],
            ["prefecture_id" => 11, "name" => "羽生市"],
            ["prefecture_id" => 11, "name" => "鴻巣市"],
            ["prefecture_id" => 11, "name" => "深谷市"],
            ["prefecture_id" => 11, "name" => "上尾市"],
            ["prefecture_id" => 11, "name" => "草加市"],
            ["prefecture_id" => 11, "name" => "越谷市"],
            ["prefecture_id" => 11, "name" => "蕨市"],
            ["prefecture_id" => 11, "name" => "戸田市"],
            ["prefecture_id" => 11, "name" => "入間市"],
            ["prefecture_id" => 11, "name" => "朝霞市"],
            ["prefecture_id" => 11, "name" => "志木市"],
            ["prefecture_id" => 11, "name" => "和光市"],
            ["prefecture_id" => 11, "name" => "新座市"],
            ["prefecture_id" => 11, "name" => "桶川市"],
            ["prefecture_id" => 11, "name" => "久喜市"],
            ["prefecture_id" => 11, "name" => "北本市"],
            ["prefecture_id" => 11, "name" => "八潮市"],
            ["prefecture_id" => 11, "name" => "富士見市"],
            ["prefecture_id" => 11, "name" => "三郷市"],
            ["prefecture_id" => 11, "name" => "蓮田市"],
            ["prefecture_id" => 11, "name" => "坂戸市"],
            ["prefecture_id" => 11, "name" => "幸手市"],
            ["prefecture_id" => 11, "name" => "鶴ヶ島市"],
            ["prefecture_id" => 11, "name" => "日高市"],
            ["prefecture_id" => 11, "name" => "吉川市"],
            ["prefecture_id" => 11, "name" => "ふじみ野市"],
            ["prefecture_id" => 11, "name" => "白岡市"],

            // 都道府県ID 12: 千葉県
            ["prefecture_id" => 12, "name" => "千葉市"],
            ["prefecture_id" => 12, "name" => "銚子市"],
            ["prefecture_id" => 12, "name" => "市川市"],
            ["prefecture_id" => 12, "name" => "船橋市"],
            ["prefecture_id" => 12, "name" => "館山市"],
            ["prefecture_id" => 12, "name" => "木更津市"],
            ["prefecture_id" => 12, "name" => "松戸市"],
            ["prefecture_id" => 12, "name" => "野田市"],
            ["prefecture_id" => 12, "name" => "茂原市"],
            ["prefecture_id" => 12, "name" => "成田市"],
            ["prefecture_id" => 12, "name" => "佐倉市"],
            ["prefecture_id" => 12, "name" => "東金市"],
            ["prefecture_id" => 12, "name" => "旭市"],
            ["prefecture_id" => 12, "name" => "習志野市"],
            ["prefecture_id" => 12, "name" => "柏市"],
            ["prefecture_id" => 12, "name" => "勝浦市"],
            ["prefecture_id" => 12, "name" => "市原市"],
            ["prefecture_id" => 12, "name" => "流山市"],
            ["prefecture_id" => 12, "name" => "八千代市"],
            ["prefecture_id" => 12, "name" => "我孫子市"],
            ["prefecture_id" => 12, "name" => "鴨川市"],
            ["prefecture_id" => 12, "name" => "鎌ケ谷市"],
            ["prefecture_id" => 12, "name" => "君津市"],
            ["prefecture_id" => 12, "name" => "富津市"],
            ["prefecture_id" => 12, "name" => "浦安市"],
            ["prefecture_id" => 12, "name" => "四街道市"],
            ["prefecture_id" => 12, "name" => "袖ケ浦市"],
            ["prefecture_id" => 12, "name" => "八街市"],
            ["prefecture_id" => 12, "name" => "印西市"],
            ["prefecture_id" => 12, "name" => "白井市"],
            ["prefecture_id" => 12, "name" => "富里市"],
            ["prefecture_id" => 12, "name" => "南房総市"],
            ["prefecture_id" => 12, "name" => "匝瑳市"],
            ["prefecture_id" => 12, "name" => "香取市"],
            ["prefecture_id" => 12, "name" => "山武市"],
            ["prefecture_id" => 12, "name" => "いすみ市"],
            ["prefecture_id" => 12, "name" => "大網白里市"],

            // 都道府県ID 13: 東京都
            ["prefecture_id" => 13, "name" => "千代田区"],
            ["prefecture_id" => 13, "name" => "中央区"],
            ["prefecture_id" => 13, "name" => "港区"],
            ["prefecture_id" => 13, "name" => "新宿区"],
            ["prefecture_id" => 13, "name" => "文京区"],
            ["prefecture_id" => 13, "name" => "台東区"],
            ["prefecture_id" => 13, "name" => "墨田区"],
            ["prefecture_id" => 13, "name" => "江東区"],
            ["prefecture_id" => 13, "name" => "品川区"],
            ["prefecture_id" => 13, "name" => "目黒区"],
            ["prefecture_id" => 13, "name" => "大田区"],
            ["prefecture_id" => 13, "name" => "世田谷区"],
            ["prefecture_id" => 13, "name" => "渋谷区"],
            ["prefecture_id" => 13, "name" => "中野区"],
            ["prefecture_id" => 13, "name" => "杉並区"],
            ["prefecture_id" => 13, "name" => "豊島区"],
            ["prefecture_id" => 13, "name" => "北区"],
            ["prefecture_id" => 13, "name" => "荒川区"],
            ["prefecture_id" => 13, "name" => "板橋区"],
            ["prefecture_id" => 13, "name" => "練馬区"],
            ["prefecture_id" => 13, "name" => "足立区"],
            ["prefecture_id" => 13, "name" => "葛飾区"],
            ["prefecture_id" => 13, "name" => "江戸川区"],
            ["prefecture_id" => 13, "name" => "八王子市"],
            ["prefecture_id" => 13, "name" => "立川市"],
            ["prefecture_id" => 13, "name" => "武蔵野市"],
            ["prefecture_id" => 13, "name" => "三鷹市"],
            ["prefecture_id" => 13, "name" => "青梅市"],
            ["prefecture_id" => 13, "name" => "府中市"],
            ["prefecture_id" => 13, "name" => "昭島市"],
            ["prefecture_id" => 13, "name" => "調布市"],
            ["prefecture_id" => 13, "name" => "町田市"],
            ["prefecture_id" => 13, "name" => "小金井市"],
            ["prefecture_id" => 13, "name" => "小平市"],
            ["prefecture_id" => 13, "name" => "日野市"],
            ["prefecture_id" => 13, "name" => "東村山市"],
            ["prefecture_id" => 13, "name" => "国分寺市"],
            ["prefecture_id" => 13, "name" => "国立市"],
            ["prefecture_id" => 13, "name" => "福生市"],
            ["prefecture_id" => 13, "name" => "狛江市"],
            ["prefecture_id" => 13, "name" => "東大和市"],
            ["prefecture_id" => 13, "name" => "清瀬市"],
            ["prefecture_id" => 13, "name" => "東久留米市"],
            ["prefecture_id" => 13, "name" => "武蔵村山市"],
            ["prefecture_id" => 13, "name" => "多摩市"],
            ["prefecture_id" => 13, "name" => "稲城市"],
            ["prefecture_id" => 13, "name" => "羽村市"],
            ["prefecture_id" => 13, "name" => "あきる野市"],
            ["prefecture_id" => 13, "name" => "西東京市"],

            // 都道府県ID 14: 神奈川県
            ["prefecture_id" => 14, "name" => "横浜市"],
            ["prefecture_id" => 14, "name" => "川崎市"],
            ["prefecture_id" => 14, "name" => "相模原市"],
            ["prefecture_id" => 14, "name" => "横須賀市"],
            ["prefecture_id" => 14, "name" => "平塚市"],
            ["prefecture_id" => 14, "name" => "鎌倉市"],
            ["prefecture_id" => 14, "name" => "藤沢市"],
            ["prefecture_id" => 14, "name" => "小田原市"],
            ["prefecture_id" => 14, "name" => "茅ヶ崎市"],
            ["prefecture_id" => 14, "name" => "逗子市"],
            ["prefecture_id" => 14, "name" => "三浦市"],
            ["prefecture_id" => 14, "name" => "秦野市"],
            ["prefecture_id" => 14, "name" => "厚木市"],
            ["prefecture_id" => 14, "name" => "大和市"],
            ["prefecture_id" => 14, "name" => "伊勢原市"],
            ["prefecture_id" => 14, "name" => "海老名市"],
            ["prefecture_id" => 14, "name" => "座間市"],
            ["prefecture_id" => 14, "name" => "南足柄市"],
            ["prefecture_id" => 14, "name" => "綾瀬市"],

            // 都道府県ID 15: 新潟県
            ["prefecture_id" => 15, "name" => "新潟市"],
            ["prefecture_id" => 15, "name" => "長岡市"],
            ["prefecture_id" => 15, "name" => "三条市"],
            ["prefecture_id" => 15, "name" => "柏崎市"],
            ["prefecture_id" => 15, "name" => "新発田市"],
            ["prefecture_id" => 15, "name" => "小千谷市"],
            ["prefecture_id" => 15, "name" => "加茂市"],
            ["prefecture_id" => 15, "name" => "十日町市"],
            ["prefecture_id" => 15, "name" => "見附市"],
            ["prefecture_id" => 15, "name" => "村上市"],
            ["prefecture_id" => 15, "name" => "燕市"],
            ["prefecture_id" => 15, "name" => "糸魚川市"],
            ["prefecture_id" => 15, "name" => "妙高市"],
            ["prefecture_id" => 15, "name" => "五泉市"],
            ["prefecture_id" => 15, "name" => "上越市"],
            ["prefecture_id" => 15, "name" => "佐渡市"],
            ["prefecture_id" => 15, "name" => "魚沼市"],
            ["prefecture_id" => 15, "name" => "南魚沼市"],
            ["prefecture_id" => 15, "name" => "胎内市"],

            // 都道府県ID 16: 富山県
            ["prefecture_id" => 16, "name" => "富山市"],
            ["prefecture_id" => 16, "name" => "高岡市"],
            ["prefecture_id" => 16, "name" => "魚津市"],
            ["prefecture_id" => 16, "name" => "氷見市"],
            ["prefecture_id" => 16, "name" => "滑川市"],
            ["prefecture_id" => 16, "name" => "黒部市"],
            ["prefecture_id" => 16, "name" => "砺波市"],
            ["prefecture_id" => 16, "name" => "小矢部市"],
            ["prefecture_id" => 16, "name" => "南砺市"],
            ["prefecture_id" => 16, "name" => "射水市"],

            // 都道府県ID 17: 石川県
            ["prefecture_id" => 17, "name" => "金沢市"],
            ["prefecture_id" => 17, "name" => "七尾市"],
            ["prefecture_id" => 17, "name" => "小松市"],
            ["prefecture_id" => 17, "name" => "輪島市"],
            ["prefecture_id" => 17, "name" => "珠洲市"],
            ["prefecture_id" => 17, "name" => "加賀市"],
            ["prefecture_id" => 17, "name" => "羽咋市"],
            ["prefecture_id" => 17, "name" => "かほく市"],
            ["prefecture_id" => 17, "name" => "白山市"],
            ["prefecture_id" => 17, "name" => "能美市"],
            ["prefecture_id" => 17, "name" => "野々市市"],

            // 都道府県ID 18: 福井県
            ["prefecture_id" => 18, "name" => "福井市"],
            ["prefecture_id" => 18, "name" => "敦賀市"],
            ["prefecture_id" => 18, "name" => "小浜市"],
            ["prefecture_id" => 18, "name" => "大野市"],
            ["prefecture_id" => 18, "name" => "勝山市"],
            ["prefecture_id" => 18, "name" => "鯖江市"],
            ["prefecture_id" => 18, "name" => "あわら市"],
            ["prefecture_id" => 18, "name" => "越前市"],
            ["prefecture_id" => 18, "name" => "坂井市"],

            // 都道府県ID 19: 山梨県
            ["prefecture_id" => 19, "name" => "甲府市"],
            ["prefecture_id" => 19, "name" => "富士吉田市"],
            ["prefecture_id" => 19, "name" => "都留市"],
            ["prefecture_id" => 19, "name" => "山梨市"],
            ["prefecture_id" => 19, "name" => "大月市"],
            ["prefecture_id" => 19, "name" => "韮崎市"],
            ["prefecture_id" => 19, "name" => "南アルプス市"],
            ["prefecture_id" => 19, "name" => "北杜市"],
            ["prefecture_id" => 19, "name" => "甲斐市"],
            ["prefecture_id" => 19, "name" => "笛吹市"],
            ["prefecture_id" => 19, "name" => "上野原市"],
            ["prefecture_id" => 19, "name" => "甲州市"],
            ["prefecture_id" => 19, "name" => "中央市"],

            // 都道府県ID 20: 長野県
            ["prefecture_id" => 20, "name" => "長野市"],
            ["prefecture_id" => 20, "name" => "松本市"],
            ["prefecture_id" => 20, "name" => "上田市"],
            ["prefecture_id" => 20, "name" => "岡谷市"],
            ["prefecture_id" => 20, "name" => "飯田市"],
            ["prefecture_id" => 20, "name" => "諏訪市"],
            ["prefecture_id" => 20, "name" => "須坂市"],
            ["prefecture_id" => 20, "name" => "小諸市"],
            ["prefecture_id" => 20, "name" => "伊那市"],
            ["prefecture_id" => 20, "name" => "駒ヶ根市"],
            ["prefecture_id" => 20, "name" => "中野市"],
            ["prefecture_id" => 20, "name" => "大町市"],
            ["prefecture_id" => 20, "name" => "飯山市"],
            ["prefecture_id" => 20, "name" => "茅野市"],
            ["prefecture_id" => 20, "name" => "佐久市"],
            ["prefecture_id" => 20, "name" => "千曲市"],
            ["prefecture_id" => 20, "name" => "東御市"],
            ["prefecture_id" => 20, "name" => "安曇野市"],

            // 都道府県ID 21: 岐阜県
            ["prefecture_id" => 21, "name" => "岐阜市"],
            ["prefecture_id" => 21, "name" => "大垣市"],
            ["prefecture_id" => 21, "name" => "高山市"],
            ["prefecture_id" => 21, "name" => "多治見市"],
            ["prefecture_id" => 21, "name" => "関市"],
            ["prefecture_id" => 21, "name" => "中津川市"],
            ["prefecture_id" => 21, "name" => "美濃市"],
            ["prefecture_id" => 21, "name" => "瑞浪市"],
            ["prefecture_id" => 21, "name" => "羽島市"],
            ["prefecture_id" => 21, "name" => "恵那市"],
            ["prefecture_id" => 21, "name" => "美濃加茂市"],
            ["prefecture_id" => 21, "name" => "土岐市"],
            ["prefecture_id" => 21, "name" => "各務原市"],
            ["prefecture_id" => 21, "name" => "可児市"],
            ["prefecture_id" => 21, "name" => "山県市"],
            ["prefecture_id" => 21, "name" => "瑞穂市"],
            ["prefecture_id" => 21, "name" => "飛騨市"],
            ["prefecture_id" => 21, "name" => "本巣市"],
            ["prefecture_id" => 21, "name" => "郡上市"],
            ["prefecture_id" => 21, "name" => "下呂市"],
            ["prefecture_id" => 21, "name" => "海津市"],

            // 都道府県ID 22: 静岡県
            ["prefecture_id" => 22, "name" => "静岡市"],
            ["prefecture_id" => 22, "name" => "浜松市"],
            ["prefecture_id" => 22, "name" => "沼津市"],
            ["prefecture_id" => 22, "name" => "熱海市"],
            ["prefecture_id" => 22, "name" => "三島市"],
            ["prefecture_id" => 22, "name" => "富士宮市"],
            ["prefecture_id" => 22, "name" => "伊東市"],
            ["prefecture_id" => 22, "name" => "島田市"],
            ["prefecture_id" => 22, "name" => "富士市"],
            ["prefecture_id" => 22, "name" => "磐田市"],
            ["prefecture_id" => 22, "name" => "焼津市"],
            ["prefecture_id" => 22, "name" => "掛川市"],
            ["prefecture_id" => 22, "name" => "藤枝市"],
            ["prefecture_id" => 22, "name" => "御殿場市"],
            ["prefecture_id" => 22, "name" => "袋井市"],
            ["prefecture_id" => 22, "name" => "下田市"],
            ["prefecture_id" => 22, "name" => "裾野市"],
            ["prefecture_id" => 22, "name" => "湖西市"],
            ["prefecture_id" => 22, "name" => "伊豆市"],
            ["prefecture_id" => 22, "name" => "御前崎市"],
            ["prefecture_id" => 22, "name" => "菊川市"],
            ["prefecture_id" => 22, "name" => "伊豆の国市"],
            ["prefecture_id" => 22, "name" => "牧之原市"],

            // 都道府県ID 23: 愛知県
            ["prefecture_id" => 23, "name" => "名古屋市"],
            ["prefecture_id" => 23, "name" => "豊橋市"],
            ["prefecture_id" => 23, "name" => "岡崎市"],
            ["prefecture_id" => 23, "name" => "一宮市"],
            ["prefecture_id" => 23, "name" => "瀬戸市"],
            ["prefecture_id" => 23, "name" => "半田市"],
            ["prefecture_id" => 23, "name" => "春日井市"],
            ["prefecture_id" => 23, "name" => "豊川市"],
            ["prefecture_id" => 23, "name" => "津島市"],
            ["prefecture_id" => 23, "name" => "碧南市"],
            ["prefecture_id" => 23, "name" => "刈谷市"],
            ["prefecture_id" => 23, "name" => "豊田市"],
            ["prefecture_id" => 23, "name" => "安城市"],
            ["prefecture_id" => 23, "name" => "西尾市"],
            ["prefecture_id" => 23, "name" => "蒲郡市"],
            ["prefecture_id" => 23, "name" => "犬山市"],
            ["prefecture_id" => 23, "name" => "常滑市"],
            ["prefecture_id" => 23, "name" => "江南市"],
            ["prefecture_id" => 23, "name" => "小牧市"],
            ["prefecture_id" => 23, "name" => "稲沢市"],
            ["prefecture_id" => 23, "name" => "新城市"],
            ["prefecture_id" => 23, "name" => "東海市"],
            ["prefecture_id" => 23, "name" => "大府市"],
            ["prefecture_id" => 23, "name" => "知多市"],
            ["prefecture_id" => 23, "name" => "知立市"],
            ["prefecture_id" => 23, "name" => "尾張旭市"],
            ["prefecture_id" => 23, "name" => "高浜市"],
            ["prefecture_id" => 23, "name" => "岩倉市"],
            ["prefecture_id" => 23, "name" => "豊明市"],
            ["prefecture_id" => 23, "name" => "日進市"],
            ["prefecture_id" => 23, "name" => "田原市"],
            ["prefecture_id" => 23, "name" => "愛西市"],
            ["prefecture_id" => 23, "name" => "清須市"],
            ["prefecture_id" => 23, "name" => "北名古屋市"],
            ["prefecture_id" => 23, "name" => "弥富市"],
            ["prefecture_id" => 23, "name" => "みよし市"],
            ["prefecture_id" => 23, "name" => "あま市"],
            ["prefecture_id" => 23, "name" => "長久手市"],

            // 都道府県ID 24: 三重県
            ["prefecture_id" => 24, "name" => "津市"],
            ["prefecture_id" => 24, "name" => "四日市市"],
            ["prefecture_id" => 24, "name" => "伊勢市"],
            ["prefecture_id" => 24, "name" => "松阪市"],
            ["prefecture_id" => 24, "name" => "桑名市"],
            ["prefecture_id" => 24, "name" => "鈴鹿市"],
            ["prefecture_id" => 24, "name" => "名張市"],
            ["prefecture_id" => 24, "name" => "尾鷲市"],
            ["prefecture_id" => 24, "name" => "亀山市"],
            ["prefecture_id" => 24, "name" => "鳥羽市"],
            ["prefecture_id" => 24, "name" => "熊野市"],
            ["prefecture_id" => 24, "name" => "いなべ市"],
            ["prefecture_id" => 24, "name" => "志摩市"],
            ["prefecture_id" => 24, "name" => "伊賀市"],

            // 都道府県ID 25: 滋賀県
            ["prefecture_id" => 25, "name" => "大津市"],
            ["prefecture_id" => 25, "name" => "彦根市"],
            ["prefecture_id" => 25, "name" => "長浜市"],
            ["prefecture_id" => 25, "name" => "近江八幡市"],
            ["prefecture_id" => 25, "name" => "草津市"],
            ["prefecture_id" => 25, "name" => "守山市"],
            ["prefecture_id" => 25, "name" => "栗東市"],
            ["prefecture_id" => 25, "name" => "甲賀市"],
            ["prefecture_id" => 25, "name" => "野洲市"],
            ["prefecture_id" => 25, "name" => "湖南市"],
            ["prefecture_id" => 25, "name" => "高島市"],
            ["prefecture_id" => 25, "name" => "東近江市"],
            ["prefecture_id" => 25, "name" => "米原市"],

            // 都道府県ID 26: 京都府
            ["prefecture_id" => 26, "name" => "京都市"],
            ["prefecture_id" => 26, "name" => "福知山市"],
            ["prefecture_id" => 26, "name" => "舞鶴市"],
            ["prefecture_id" => 26, "name" => "綾部市"],
            ["prefecture_id" => 26, "name" => "宇治市"],
            ["prefecture_id" => 26, "name" => "宮津市"],
            ["prefecture_id" => 26, "name" => "亀岡市"],
            ["prefecture_id" => 26, "name" => "城陽市"],
            ["prefecture_id" => 26, "name" => "向日市"],
            ["prefecture_id" => 26, "name" => "長岡京市"],
            ["prefecture_id" => 26, "name" => "八幡市"],
            ["prefecture_id" => 26, "name" => "京田辺市"],
            ["prefecture_id" => 26, "name" => "京丹後市"],
            ["prefecture_id" => 26, "name" => "南丹市"],
            ["prefecture_id" => 26, "name" => "木津川市"],

            // 都道府県ID 27: 大阪府
            ["prefecture_id" => 27, "name" => "大阪市"],
            ["prefecture_id" => 27, "name" => "堺市"],
            ["prefecture_id" => 27, "name" => "岸和田市"],
            ["prefecture_id" => 27, "name" => "豊中市"],
            ["prefecture_id" => 27, "name" => "池田市"],
            ["prefecture_id" => 27, "name" => "吹田市"],
            ["prefecture_id" => 27, "name" => "泉大津市"],
            ["prefecture_id" => 27, "name" => "高槻市"],
            ["prefecture_id" => 27, "name" => "貝塚市"],
            ["prefecture_id" => 27, "name" => "守口市"],
            ["prefecture_id" => 27, "name" => "枚方市"],
            ["prefecture_id" => 27, "name" => "茨木市"],
            ["prefecture_id" => 27, "name" => "八尾市"],
            ["prefecture_id" => 27, "name" => "泉佐野市"],
            ["prefecture_id" => 27, "name" => "富田林市"],
            ["prefecture_id" => 27, "name" => "寝屋川市"],
            ["prefecture_id" => 27, "name" => "河内長野市"],
            ["prefecture_id" => 27, "name" => "松原市"],
            ["prefecture_id" => 27, "name" => "大東市"],
            ["prefecture_id" => 27, "name" => "和泉市"],
            ["prefecture_id" => 27, "name" => "箕面市"],
            ["prefecture_id" => 27, "name" => "柏原市"],
            ["prefecture_id" => 27, "name" => "羽曳野市"],
            ["prefecture_id" => 27, "name" => "門真市"],
            ["prefecture_id" => 27, "name" => "摂津市"],
            ["prefecture_id" => 27, "name" => "高石市"],
            ["prefecture_id" => 27, "name" => "藤井寺市"],
            ["prefecture_id" => 27, "name" => "東大阪市"],
            ["prefecture_id" => 27, "name" => "泉南市"],
            ["prefecture_id" => 27, "name" => "四條畷市"],
            ["prefecture_id" => 27, "name" => "交野市"],
            ["prefecture_id" => 27, "name" => "大阪狭山市"],
            ["prefecture_id" => 27, "name" => "阪南市"],

            // 都道府県ID 28: 兵庫県
            ["prefecture_id" => 28, "name" => "神戸市"],
            ["prefecture_id" => 28, "name" => "姫路市"],
            ["prefecture_id" => 28, "name" => "尼崎市"],
            ["prefecture_id" => 28, "name" => "明石市"],
            ["prefecture_id" => 28, "name" => "西宮市"],
            ["prefecture_id" => 28, "name" => "洲本市"],
            ["prefecture_id" => 28, "name" => "芦屋市"],
            ["prefecture_id" => 28, "name" => "伊丹市"],
            ["prefecture_id" => 28, "name" => "相生市"],
            ["prefecture_id" => 28, "name" => "豊岡市"],
            ["prefecture_id" => 28, "name" => "加古川市"],
            ["prefecture_id" => 28, "name" => "赤穂市"],
            ["prefecture_id" => 28, "name" => "西脇市"],
            ["prefecture_id" => 28, "name" => "宝塚市"],
            ["prefecture_id" => 28, "name" => "三木市"],
            ["prefecture_id" => 28, "name" => "高砂市"],
            ["prefecture_id" => 28, "name" => "川西市"],
            ["prefecture_id" => 28, "name" => "小野市"],
            ["prefecture_id" => 28, "name" => "三田市"],
            ["prefecture_id" => 28, "name" => "加西市"],
            ["prefecture_id" => 28, "name" => "丹波篠山市"],
            ["prefecture_id" => 28, "name" => "養父市"],
            ["prefecture_id" => 28, "name" => "丹波市"],
            ["prefecture_id" => 28, "name" => "南あわじ市"],
            ["prefecture_id" => 28, "name" => "朝来市"],
            ["prefecture_id" => 28, "name" => "宍粟市"],
            ["prefecture_id" => 28, "name" => "加東市"],
            ["prefecture_id" => 28, "name" => "たつの市"],

            // 都道府県ID 29: 奈良県
            ["prefecture_id" => 29, "name" => "奈良市"],
            ["prefecture_id" => 29, "name" => "大和高田市"],
            ["prefecture_id" => 29, "name" => "大和郡山市"],
            ["prefecture_id" => 29, "name" => "天理市"],
            ["prefecture_id" => 29, "name" => "橿原市"],
            ["prefecture_id" => 29, "name" => "桜井市"],
            ["prefecture_id" => 29, "name" => "五條市"],
            ["prefecture_id" => 29, "name" => "御所市"],
            ["prefecture_id" => 29, "name" => "生駒市"],
            ["prefecture_id" => 29, "name" => "香芝市"],
            ["prefecture_id" => 29, "name" => "葛城市"],
            ["prefecture_id" => 29, "name" => "宇陀市"],

            // 都道府県ID 30: 和歌山県
            ["prefecture_id" => 30, "name" => "和歌山市"],
            ["prefecture_id" => 30, "name" => "海南市"],
            ["prefecture_id" => 30, "name" => "橋本市"],
            ["prefecture_id" => 30, "name" => "有田市"],
            ["prefecture_id" => 30, "name" => "御坊市"],
            ["prefecture_id" => 30, "name" => "田辺市"],
            ["prefecture_id" => 30, "name" => "新宮市"],
            ["prefecture_id" => 30, "name" => "紀の川市"],
            ["prefecture_id" => 30, "name" => "岩出市"],

            // 都道府県ID 31: 鳥取県
            ["prefecture_id" => 31, "name" => "鳥取市"],
            ["prefecture_id" => 31, "name" => "米子市"],
            ["prefecture_id" => 31, "name" => "倉吉市"],
            ["prefecture_id" => 31, "name" => "境港市"],

            // 都道府県ID 32: 島根県
            ["prefecture_id" => 32, "name" => "松江市"],
            ["prefecture_id" => 32, "name" => "浜田市"],
            ["prefecture_id" => 32, "name" => "出雲市"],
            ["prefecture_id" => 32, "name" => "益田市"],
            ["prefecture_id" => 32, "name" => "大田市"],
            ["prefecture_id" => 32, "name" => "安来市"],
            ["prefecture_id" => 32, "name" => "江津市"],
            ["prefecture_id" => 32, "name" => "雲南市"],

            // 都道府県ID 33: 岡山県
            ["prefecture_id" => 33, "name" => "岡山市"],
            ["prefecture_id" => 33, "name" => "倉敷市"],
            ["prefecture_id" => 33, "name" => "津山市"],
            ["prefecture_id" => 33, "name" => "玉野市"],
            ["prefecture_id" => 33, "name" => "笠岡市"],
            ["prefecture_id" => 33, "name" => "井原市"],
            ["prefecture_id" => 33, "name" => "総社市"],
            ["prefecture_id" => 33, "name" => "高梁市"],
            ["prefecture_id" => 33, "name" => "新見市"],
            ["prefecture_id" => 33, "name" => "備前市"],
            ["prefecture_id" => 33, "name" => "瀬戸内市"],
            ["prefecture_id" => 33, "name" => "赤磐市"],
            ["prefecture_id" => 33, "name" => "真庭市"],
            ["prefecture_id" => 33, "name" => "美作市"],
            ["prefecture_id" => 33, "name" => "浅口市"],

            // 都道府県ID 34: 広島県
            ["prefecture_id" => 34, "name" => "広島市"],
            ["prefecture_id" => 34, "name" => "呉市"],
            ["prefecture_id" => 34, "name" => "竹原市"],
            ["prefecture_id" => 34, "name" => "三原市"],
            ["prefecture_id" => 34, "name" => "尾道市"],
            ["prefecture_id" => 34, "name" => "福山市"],
            ["prefecture_id" => 34, "name" => "府中市"],
            ["prefecture_id" => 34, "name" => "三次市"],
            ["prefecture_id" => 34, "name" => "庄原市"],
            ["prefecture_id" => 34, "name" => "大竹市"],
            ["prefecture_id" => 34, "name" => "東広島市"],
            ["prefecture_id" => 34, "name" => "廿日市市"],
            ["prefecture_id" => 34, "name" => "安芸高田市"],
            ["prefecture_id" => 34, "name" => "江田島市"],

            // 都道府県ID 35: 山口県
            ["prefecture_id" => 35, "name" => "下関市"],
            ["prefecture_id" => 35, "name" => "宇部市"],
            ["prefecture_id" => 35, "name" => "山口市"],
            ["prefecture_id" => 35, "name" => "萩市"],
            ["prefecture_id" => 35, "name" => "防府市"],
            ["prefecture_id" => 35, "name" => "下松市"],
            ["prefecture_id" => 35, "name" => "岩国市"],
            ["prefecture_id" => 35, "name" => "光市"],
            ["prefecture_id" => 35, "name" => "長門市"],
            ["prefecture_id" => 35, "name" => "柳井市"],
            ["prefecture_id" => 35, "name" => "美祢市"],
            ["prefecture_id" => 35, "name" => "周南市"],
            ["prefecture_id" => 35, "name" => "山陽小野田市"],

            // 都道府県ID 36: 徳島県
            ["prefecture_id" => 36, "name" => "徳島市"],
            ["prefecture_id" => 36, "name" => "鳴門市"],
            ["prefecture_id" => 36, "name" => "小松島市"],
            ["prefecture_id" => 36, "name" => "阿南市"],
            ["prefecture_id" => 36, "name" => "吉野川市"],
            ["prefecture_id" => 36, "name" => "阿波市"],
            ["prefecture_id" => 36, "name" => "美馬市"],
            ["prefecture_id" => 36, "name" => "三好市"],

            // 都道府県ID 37: 香川県
            ["prefecture_id" => 37, "name" => "高松市"],
            ["prefecture_id" => 37, "name" => "丸亀市"],
            ["prefecture_id" => 37, "name" => "坂出市"],
            ["prefecture_id" => 37, "name" => "善通寺市"],
            ["prefecture_id" => 37, "name" => "観音寺市"],
            ["prefecture_id" => 37, "name" => "さぬき市"],
            ["prefecture_id" => 37, "name" => "東かがわ市"],
            ["prefecture_id" => 37, "name" => "三豊市"],

            // 都道府県ID 38: 愛媛県
            ["prefecture_id" => 38, "name" => "松山市"],
            ["prefecture_id" => 38, "name" => "今治市"],
            ["prefecture_id" => 38, "name" => "宇和島市"],
            ["prefecture_id" => 38, "name" => "八幡浜市"],
            ["prefecture_id" => 38, "name" => "新居浜市"],
            ["prefecture_id" => 38, "name" => "西条市"],
            ["prefecture_id" => 38, "name" => "大洲市"],
            ["prefecture_id" => 38, "name" => "伊予市"],
            ["prefecture_id" => 38, "name" => "四国中央市"],
            ["prefecture_id" => 38, "name" => "西予市"],
            ["prefecture_id" => 38, "name" => "東温市"],

            // 都道府県ID 39: 高知県
            ["prefecture_id" => 39, "name" => "高知市"],
            ["prefecture_id" => 39, "name" => "室戸市"],
            ["prefecture_id" => 39, "name" => "安芸市"],
            ["prefecture_id" => 39, "name" => "南国市"],
            ["prefecture_id" => 39, "name" => "土佐市"],
            ["prefecture_id" => 39, "name" => "須崎市"],
            ["prefecture_id" => 39, "name" => "宿毛市"],
            ["prefecture_id" => 39, "name" => "土佐清水市"],
            ["prefecture_id" => 39, "name" => "四万十市"],
            ["prefecture_id" => 39, "name" => "香南市"],
            ["prefecture_id" => 39, "name" => "香美市"],

            // 都道府県ID 40: 福岡県
            ["prefecture_id" => 40, "name" => "北九州市"],
            ["prefecture_id" => 40, "name" => "福岡市"],
            ["prefecture_id" => 40, "name" => "大牟田市"],
            ["prefecture_id" => 40, "name" => "久留米市"],
            ["prefecture_id" => 40, "name" => "直方市"],
            ["prefecture_id" => 40, "name" => "飯塚市"],
            ["prefecture_id" => 40, "name" => "田川市"],
            ["prefecture_id" => 40, "name" => "柳川市"],
            ["prefecture_id" => 40, "name" => "八女市"],
            ["prefecture_id" => 40, "name" => "筑後市"],
            ["prefecture_id" => 40, "name" => "大川市"],
            ["prefecture_id" => 40, "name" => "行橋市"],
            ["prefecture_id" => 40, "name" => "豊前市"],
            ["prefecture_id" => 40, "name" => "中間市"],
            ["prefecture_id" => 40, "name" => "小郡市"],
            ["prefecture_id" => 40, "name" => "筑紫野市"],
            ["prefecture_id" => 40, "name" => "春日市"],
            ["prefecture_id" => 40, "name" => "大野城市"],
            ["prefecture_id" => 40, "name" => "宗像市"],
            ["prefecture_id" => 40, "name" => "太宰府市"],
            ["prefecture_id" => 40, "name" => "古賀市"],
            ["prefecture_id" => 40, "name" => "福津市"],
            ["prefecture_id" => 40, "name" => "うきは市"],
            ["prefecture_id" => 40, "name" => "宮若市"],
            ["prefecture_id" => 40, "name" => "朝倉市"],
            ["prefecture_id" => 40, "name" => "嘉麻市"],
            ["prefecture_id" => 40, "name" => "みやま市"],
            ["prefecture_id" => 40, "name" => "糸島市"],

            // 都道府県ID 41: 佐賀県
            ["prefecture_id" => 41, "name" => "佐賀市"],
            ["prefecture_id" => 41, "name" => "唐津市"],
            ["prefecture_id" => 41, "name" => "鳥栖市"],
            ["prefecture_id" => 41, "name" => "多久市"],
            ["prefecture_id" => 41, "name" => "伊万里市"],
            ["prefecture_id" => 41, "name" => "武雄市"],
            ["prefecture_id" => 41, "name" => "鹿島市"],
            ["prefecture_id" => 41, "name" => "小城市"],
            ["prefecture_id" => 41, "name" => "嬉野市"],
            ["prefecture_id" => 41, "name" => "神埼市"],

            // 都道府県ID 42: 長崎県
            ["prefecture_id" => 42, "name" => "長崎市"],
            ["prefecture_id" => 42, "name" => "佐世保市"],
            ["prefecture_id" => 42, "name" => "島原市"],
            ["prefecture_id" => 42, "name" => "諫早市"],
            ["prefecture_id" => 42, "name" => "大村市"],
            ["prefecture_id" => 42, "name" => "平戸市"],
            ["prefecture_id" => 42, "name" => "松浦市"],
            ["prefecture_id" => 42, "name" => "対馬市"],
            ["prefecture_id" => 42, "name" => "壱岐市"],
            ["prefecture_id" => 42, "name" => "五島市"],
            ["prefecture_id" => 42, "name" => "西海市"],
            ["prefecture_id" => 42, "name" => "雲仙市"],
            ["prefecture_id" => 42, "name" => "南島原市"],

            // 都道府県ID 43: 熊本県
            ["prefecture_id" => 43, "name" => "熊本市"],
            ["prefecture_id" => 43, "name" => "八代市"],
            ["prefecture_id" => 43, "name" => "人吉市"],
            ["prefecture_id" => 43, "name" => "荒尾市"],
            ["prefecture_id" => 43, "name" => "水俣市"],
            ["prefecture_id" => 43, "name" => "玉名市"],
            ["prefecture_id" => 43, "name" => "山鹿市"],
            ["prefecture_id" => 43, "name" => "菊池市"],
            ["prefecture_id" => 43, "name" => "宇土市"],
            ["prefecture_id" => 43, "name" => "上天草市"],
            ["prefecture_id" => 43, "name" => "宇城市"],
            ["prefecture_id" => 43, "name" => "阿蘇市"],
            ["prefecture_id" => 43, "name" => "天草市"],
            ["prefecture_id" => 43, "name" => "合志市"],

            // 都道府県ID 44: 大分県
            ["prefecture_id" => 44, "name" => "大分市"],
            ["prefecture_id" => 44, "name" => "別府市"],
            ["prefecture_id" => 44, "name" => "中津市"],
            ["prefecture_id" => 44, "name" => "日田市"],
            ["prefecture_id" => 44, "name" => "佐伯市"],
            ["prefecture_id" => 44, "name" => "臼杵市"],
            ["prefecture_id" => 44, "name" => "津久見市"],
            ["prefecture_id" => 44, "name" => "竹田市"],
            ["prefecture_id" => 44, "name" => "豊後高田市"],
            ["prefecture_id" => 44, "name" => "杵築市"],
            ["prefecture_id" => 44, "name" => "宇佐市"],
            ["prefecture_id" => 44, "name" => "豊後大野市"],
            ["prefecture_id" => 44, "name" => "由布市"],
            ["prefecture_id" => 44, "name" => "国東市"],

            // 都道府県ID 45: 宮崎県
            ["prefecture_id" => 45, "name" => "宮崎市"],
            ["prefecture_id" => 45, "name" => "都城市"],
            ["prefecture_id" => 45, "name" => "延岡市"],
            ["prefecture_id" => 45, "name" => "日南市"],
            ["prefecture_id" => 45, "name" => "小林市"],
            ["prefecture_id" => 45, "name" => "日向市"],
            ["prefecture_id" => 45, "name" => "串間市"],
            ["prefecture_id" => 45, "name" => "西都市"],
            ["prefecture_id" => 45, "name" => "えびの市"],

            // 都道府県ID 46: 鹿児島県
            ["prefecture_id" => 46, "name" => "鹿児島市"],
            ["prefecture_id" => 46, "name" => "鹿屋市"],
            ["prefecture_id" => 46, "name" => "枕崎市"],
            ["prefecture_id" => 46, "name" => "阿久根市"],
            ["prefecture_id" => 46, "name" => "出水市"],
            ["prefecture_id" => 46, "name" => "指宿市"],
            ["prefecture_id" => 46, "name" => "西之表市"],
            ["prefecture_id" => 46, "name" => "垂水市"],
            ["prefecture_id" => 46, "name" => "薩摩川内市"],
            ["prefecture_id" => 46, "name" => "日置市"],
            ["prefecture_id" => 46, "name" => "曽於市"],
            ["prefecture_id" => 46, "name" => "霧島市"],
            ["prefecture_id" => 46, "name" => "いちき串木野市"],
            ["prefecture_id" => 46, "name" => "南さつま市"],
            ["prefecture_id" => 46, "name" => "志布志市"],
            ["prefecture_id" => 46, "name" => "奄美市"],
            ["prefecture_id" => 46, "name" => "南九州市"],
            ["prefecture_id" => 46, "name" => "伊佐市"],

            // 都道府県ID 47: 沖縄県
            ["prefecture_id" => 47, "name" => "那覇市"],
            ["prefecture_id" => 47, "name" => "宜野湾市"],
            ["prefecture_id" => 47, "name" => "石垣市"],
            ["prefecture_id" => 47, "name" => "浦添市"],
            ["prefecture_id" => 47, "name" => "名護市"],
            ["prefecture_id" => 47, "name" => "糸満市"],
            ["prefecture_id" => 47, "name" => "沖縄市"],
            ["prefecture_id" => 47, "name" => "豊見城市"],
            ["prefecture_id" => 47, "name" => "うるま市"],
            ["prefecture_id" => 47, "name" => "宮古島市"],
            ["prefecture_id" => 47, "name" => "南城市"],
        ];

        foreach ($cities as  $city) {
            DB::table('cities')->insert($city);
        }
    }
}
